### ISSUE TITLE
ParamSpace registered again in class2 upgrade

### ISSUE THREAD

**Issue by chengwenxi** [irisnet/irishub#1003]
**Describe the bug**
We define a map ParamSetMapping in https://github.com/irisnet/irishub/blob/develop/modules/params/helper.go#L9
to store the ParamSet.

When a software upgrade proposal passed and then load the new protocol version will call function RegisterParamSet again, it lead to panic at
https://github.com/irisnet/irishub/blob/develop/modules/params/helper.go#L15

**Solution**
A. Don't check ParamSpace is already registered
B. When load a new protocol version reset ParamSetMapping

Some advice about it? @haifengxi @wukongcheng @MrXJC

**Comment by chengwenxi** [comment]
I think ParamSetMapping should be a parameter of `protocol`.

**Comment by wukongcheng** [comment]
It seems the `ParamSetMapping` should be a part of the protocol. Of course, reset ParamSetMapping when switching versions, will be the minimum changes to the codes.

**Comment by haifengxi** [comment]
Let's use Option B.

**Comment by chengwenxi** [comment]
It's confusing to define a  parameter `ParamSetMapping` which not be part of IrisApp, why not add `ParamSetMapping` in params Keeper?https://github.com/irisnet/irishub/blob/develop/modules/params/keeper.go#L11

**Comment by haifengxi** [comment]
> It's confusing to define a map `ParamSetMapping` which not be part of IrisApp, why not add `ParamSetMapping` in params Keeper?https://github.com/irisnet/irishub/blob/develop/modules/params/keeper.go#L11

Nice choice!  When we configure the params keeper for a new protocol, the `ParamSetMapping` within will be initialized as a new one.
