### ISSUE TITLE
Important business rule missing in the gov spec

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1006]
Important functional point is omitted in newgov spec :
The Deposit would be totally burned while the number of NoWithVeto is > 1/3

https://gitlab.bianjie.ai/irishub/internal-spec/blob/silei/spec/gov/NewGov.md

----------------------------------
iris version 3894c521bd7d6b83075262026b6dfaa395808bae
0.10.0-rc0-3894c52-0

**Comment by wukongcheng** [comment]
Thanks. We will update the spec soon.

**Comment by haifengxi** [comment]
Please help update the spec, thanks. @shilei-wang
