### ISSUE TITLE
本地节点追赶同步区块阶段，发的转账交易无法上链问题

### ISSUE THREAD

**Issue by huang0227** [irisnet/irishub#1012]
在irishub0.9.0上，本地节点处于追赶同步区块阶段，本地发起转账，此时交易是不会上链的。有问题。
因为根据需求正确格式的交易在追赶同步区块时是可以上链的，此时发起第一条提议就会上链，没问题，之后再把刚才的提议命令发送时，会报 RPC error -32603 - Internal error: Error on broadcastTxCommit: Tx already exists in cache。 如果再发一次提议，命令中的from的值换一个，此时会报ERROR: {"codespace":"sdk","code":3,"message":"Invalid sequence. Got 6, expected 7"}，这些逻辑都对。

**Comment by wukongcheng** [comment]
Try to reproduce and locate the issue. @MrXJC

**Comment by MrXJC** [comment]
Translate this issue into English.

Issue: Send the txs to the node which is syncing the blocks, it will report `Timeout Error`. After the node finish syncing the blocks, some transcations  include the block and others don‘t include the block.
