### ISSUE TITLE
[p3] Unit dislocation in ERROR message of ParameterChange/slashing

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1014]
echo 1234567890 | iriscli gov submit-proposal --title="t" --description="t" --type="ParameterChange" --deposit="2000iris"  --param='slashing/SlashFractionDoubleSign=0.11' --from=v0 --chain-id=shilei-qa --fee=0.004iris  --commit

ERROR: {"codespace":"sdk","code":800,"message":"Slash MinSignedPerWindow/SlashFractionDoubleSign/SlashFractionDowntime [1100000000] should be between [0.01, 0.1] "}

should be ： 【 [0.11] should be between [0.01, 0.1] 】

---------
echo 1234567890 | iriscli gov submit-proposal --title="t" --description="t" --type="ParameterChange" --deposit="2000iris"  --param='slashing/SlashFractionDowntime=0.004' --from=v0 --chain-id=shilei-qa --fee=0.004iris  --commit

ERROR: {"codespace":"sdk","code":800,"message":"Slash MinSignedPerWindow/SlashFractionDoubleSign/SlashFractionDowntime [40000000] should be between [0.005, 0.1] "}

should be ： 【 [0.004] should be between [0.01, 0.1] 】

----------------------------------
iris version 3894c521bd7d6b83075262026b6dfaa395808bae
0.10.0-rc0-3894c52-0

**Comment by wukongcheng** [comment]
Fix both on develop and release0.10 branch @MrXJC

**Comment by shilei-wang** [comment]
verified
