### ISSUE TITLE
[p1] Attempts to change parameter slashing/MaxEvidenceAge always fail

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1015]
No matter what value is set, ParameterChange proposal will be rejected anyway.

echo 1234567890 | iriscli gov submit-proposal --title="t" --description="t" --type="ParameterChange" --deposit="2000iris"  --param='slashing/MaxEvidenceAge=24h0m0s' --from=v0 --chain-id=shilei-qa --fee=0.004iris  --commit

ERROR: {"codespace":"sdk","code":800,"message":"Slash MaxEvidenceAge [0s] should be between [10min,) "}

----------------------------------
iris version 3894c521bd7d6b83075262026b6dfaa395808bae
0.10.0-rc0-3894c52-0

**Comment by wukongcheng** [comment]
Need to be fix in release0.10 and develop branch. @MrXJC

**Comment by shilei-wang** [comment]
verified
