### ISSUE TITLE
[priority:p0]  The TX size Service Define consumed far greater than 1000bytes, which causes no service can be defined under this limitation.

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1037]
echo 1234567890 | iriscli service define --chain-id=shilei-qa  --from=v0 --fee=0.004iris --service-description=service-description --author-description=author-description --tags=tag1,tag2 --idl-content=idl-content --file=/root/test.proto --service-name=001 --commit

ERROR: {"codespace":"sdk","code":21,"message":"the tx size exceeds the limitation"}

----------------
We must think it over carefully.
v0.11.0-Alpha  5acf8729120504d0e895fef8188b02ffd0da1f94

**Comment by haifengxi** [comment]
Service module will be upgraded so that service definitions will be stored off-chain (in decentralized storage network) and only references are included in the tx msg.  Closing this issue for now.
