### ISSUE TITLE
[p2] Create-validator fail to check the scope of commission-rate/commission-max-change-rate/commission-rate， param 0,0,0 can be set

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1064]
Once param (--commission-max-change-rate=0) is set, then we could not modify commission rate any more!

echo 1234567890 | iriscli stake create-validator --pubkey=fcp1zcjduepqtq77rjchyqjuhplcyrnehfrtfnu94cdg9nud25rjnazvjf58hh3swgldyj --moniker=2 --amount=1iris --fee=0.004iris --commit --from=v1 --chain-id=shilei-qa --commission-max-change-rate=0 --commission-max-rate=0 --commission-rate=0

Validator with params(commission=0,0,0) created

**Comment by HaoyangLiu** [comment]
This is an expected behavior, not a bug.

**Comment by wukongcheng** [comment]
Agree that this is not a bug. The Validator was specified that the rate cannot be modified when CreateValidator. But we can give hints and confirmations when CreateValidator
