### ISSUE TITLE
Return of iriscli gov query-params is wrong

### ISSUE THREAD

**Issue by kidinamoto01** [irisnet/irishub#1096]
**Describe the bug**
query result of governance parameter should be more precise

**To Reproduce**
Run the following command,
```
iriscli gov query-params --module=gov --node=localhost:46657
```
It returns:
```
ERROR: ERROR:
Codespace: params
Code: 111
Message: "gov/CriticalDepositPeriod is not found
```
**Expected behavior**
it should returns sth like:
```
gov module not eligible for parameter querying
```
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by haifengxi** [comment]
Bug report should always include the version information of software in question. @kidinamoto01
