### ISSUE TITLE
Keep track of important Tendermint issues and PRs

### ISSUE THREAD

**Issue by HaoyangLiu** [irisnet/irishub#1137]
1. mempool: wasteful tx broadcasting
https://github.com/tendermint/tendermint/issues/1798
2. mempool no gossip back
https://github.com/tendermint/tendermint/pull/2778
3. ABCI / mempool: Add a "Recheck Tx" function
https://github.com/tendermint/tendermint/issues/2127
4. Round synchronisation could be very slow
https://github.com/tendermint/tendermint/issues/1496
5. fix DynamicVerifier for large validator set changes
https://github.com/tendermint/tendermint/pull/3171
6. RPC Evidence Endpoint
https://github.com/tendermint/tendermint/pull/2630
7. consensus: disconnect from bad peers
https://github.com/tendermint/tendermint/issues/2871
8. Tendermint on non-deterministic signatures
https://github.com/tendermint/tendermint/issues/1664
9. abci: RequestDeliverTx and RequestCheckTx
https://github.com/tendermint/tendermint/issues/3193
10. p2p: file descriptor leaks
https://github.com/tendermint/tendermint/pull/3150

**Comment by haifengxi** [comment]
Will keep track of Tendermint issues in irisnet/tendermint instead.
