### ISSUE TITLE
Design and implement the global system level monitor metrics 

### ISSUE THREAD

**Issue by wukongcheng** [irisnet/irishub#1188]
- app hash conflict
- consensus failure
- no block produce
- resource leak

**Comment by HaoyangLiu** [comment]
1. no block produce: This can be monitored by [round](https://github.com/irisnet/tendermint/blob/7dfe2e8443c92c416c91f76fdf934ebf0ae9cfc4/consensus/metrics.go#L19)
2. resource leak: This can be tracked by these items: `go_goroutines`, `go_memstats_alloc_bytes`, `go_memstats_heap_alloc_bytes`. These items have already be monitored.

**Comment by wukongcheng** [comment]
> 1. no block produce: This can be monitored by [round](https://github.com/irisnet/tendermint/blob/7dfe2e8443c92c416c91f76fdf934ebf0ae9cfc4/consensus/metrics.go#L19)
> 2. resource leak: This can be tracked by these items: `go_goroutines`, `go_memstats_alloc_bytes`, `go_memstats_heap_alloc_bytes`. These items have already be monitored.

Make sense.
