### ISSUE TITLE
Sending a transaction with a Ledger Nano S fails

### ISSUE THREAD

**Issue by adrianbrink** [irisnet/irishub#1218]
**Describe the bug**
Sending a transaction from a Nano Ledger S fails with
```
➜  irishub git:(ae1e4917) ✗ iriscli bank send --to=faa1p8n6pkrzsau5nfvvl46sdaxj9dpeuqe5fle9tw --ledger --from=test_ledger --fee=4iris --chain-id=fuxi-8000 --amount=4iris --node="tcp://35.198.105.81:26657"
ERROR: please open Cosmos app on the Ledger device - error: error fetching public key: lost connection
```

I am using the Cosmos ledger application, which does work in order to register it with the iriscli.

**To Reproduce**
1. Register the Ledger with the iriscli
2. Send tokens to the ledger address
3. Send tokens from the ledger address to someone else

**Expected behavior**
Sending tokens from a ledger account should work.

**Desktop (please complete the following information):**
```
➜  irishub git:(ae1e4917) ✗ iriscli version
0.11.0-ae1e4917-0
```

**Additional Information**
riot id: @adrianbrink:matrix.org

**Comment by haifengxi** [comment]
We have started working on supporting Ledger Nano S.  Thanks for bearing with us.
