### ISSUE TITLE
Review and improve all CLI & LCD APIs

### ISSUE THREAD

**Issue by wukongcheng** [irisnet/irishub#1245]

**Comment by HaoyangLiu** [comment]
Arrangement:

@HaoyangLiu 
- ICS21 Stake module APIs
- ICS23 Slashing module APIs
- ICS24 Distribution module APIs

@wukongcheng 
- ICS0 Tendermint APIs, such as query blocks, transactions and validatorset
- ICS22 Governance module APIs

@chengwenxi 
- ICS1 Key management APIs
- ICS20 Create, sign and broadcast transactions
- ICS25 Service module APIs

**Comment by chengwenxi** [comment]
We should also improve the CLI APIS.

Target:
* Move sign and broadcast to tx
* Remove tx/send
* Normalize REST APIs by https://restfulapi.net/resource-naming/
