### ISSUE TITLE
[p3] Incorrect calculation of Gas Simulation

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1248]
**Describe the bug**
Incorrect calculation of Gas Simulation while using --gas="simulate"
estimated gas is not corrent
simulation log is un-readable

**To Reproduce**
echo 1234567890 | iriscli stake unbond --address-validator=fva1xs5c6fjtwcgp036kez7mt75g8vmp9m4pl2tash --shares-amount=1 --fee=0.004iris --from=v1 --commit --chain-id=shilei-qa --gas="simulate"

estimated gas = 77
simulation code = 18
simulation log = {"codespace":"sdk","code":18,"message":"gaslimit 0 should be positive and no more than 9223372036854775807"}
simulation gas wanted = 0
simulation gas used = 77
simulation fee amount = 0
simulation fee denom =

**Comment by HaoyangLiu** [comment]
fixed
