### ISSUE TITLE
[p3] [lcd] Improper "Panic Message" returned when 2 different irislcd using the same HOME

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1258]
**Describe the bug**
Improper "Panic Message" returned 

**To Reproduce**
step1： irislcd start --node=tcp://localhost:26657 --laddr=tcp://0.0.0.0:30317 --chain-id=shilei-qa --home=$HOME/.iriscli/

step2： irislcd start --node=tcp://localhost:26657 --laddr=tcp://0.0.0.0:30317 --chain-id=shilei-qa --home=$HOME/.iriscli/

goroutine 1 [running]:
github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/libs/db.NewDB(0xedc14d, 0xa, 0xed9372, 0x7, 0xc000a6e030, 0xe, 0xda3001, 0xc00000cee0)
	/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/libs/db/db.go:51 +0x2a0
github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/lite/proxy.NewVerifier(0x7ffe95ed339e, 0x9, 0xc000a6e030, 0xe, 0x134e220, 0xc00000cee0, 0x1349c40, 0x1ae9820, 0xa, 0xc0004a15d0, ...)
	/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/lite/proxy/verifier.go:17 +0x35e
github.com/irisnet/irishub/client/context.createVerifier(0xedf0e6, 0xe)
	/root/go/src/github.com/irisnet/irishub/client/context/context.go:114 +0x309
github.com/irisnet/irishub/client/context.NewCLIContext(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/go/src/github.com/irisnet/irishub/client/context/context.go:73 +0x204
github.com/irisnet/irishub/lite.createHandler(0xc0000f0fc0, 0x5)
	/root/go/src/github.com/irisnet/irishub/lite/lcd.go:93 +0x82
github.com/irisnet/irishub/lite.ServeLCDStartCommand.func1(0xc0000cfd40, 0xc0001a2720, 0x0, 0x3, 0x0, 0x0)
	/root/go/src/github.com/irisnet/irishub/lite/lcd.go:40 +0x8e
github.com/irisnet/irishub/vendor/github.com/spf13/cobra.(*Command).execute(0xc0000cfd40, 0xc0001a2660, 0x3, 0x3, 0xc0000cfd40, 0xc0001a2660)
	/root/go/src/github.com/irisnet/irishub/vendor/github.com/spf13/cobra/command.go:698 +0x47a
github.com/irisnet/irishub/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1abeae0, 0x24, 0xc000a6eba6, 0xeee976)
	/root/go/src/github.com/irisnet/irishub/vendor/github.com/spf13/cobra/command.go:783 +0x2dc
github.com/irisnet/irishub/vendor/github.com/spf13/cobra.(*Command).Execute(0x1abeae0, 0x1, 0xc0001c46e0)
	/root/go/src/github.com/irisnet/irishub/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/libs/cli.Executor.Execute(0x1abeae0, 0x127a680, 0x7, 0xc000a6e030)
	/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/libs/cli/setup.go:89 +0x4e
main.main()
	/root/go/src/github.com/irisnet/irishub/cmd/irislcd/main.go:32 +0xf0

**Comment by HaoyangLiu** [comment]
This is the current panic error message:
```
panic: Error initializing DB: resource temporarily unavailable

goroutine 1 [running]:
github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/libs/db.NewDB(0xef3017, 0xa, 0xef022c, 0x7, 0xc000a10e20, 0x15, 0xdb8401, 0xc000ad6f80)
        /home/lhy/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/libs/db/db.go:51 +0x2a0
github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/lite/proxy.NewVerifier(0x7ffcbd9c378f, 0x7, 0xc000a10e20, 0x15, 0x1365d60, 0xc000ad6f80, 0x1361780, 0x1d0c8f8, 0xa, 0xc0007a15d0, ...)
        /home/lhy/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/lite/proxy/verifier.go:17 +0x35e
github.com/irisnet/irishub/client/context.createVerifier(0xef5fe9, 0xe)
        /home/lhy/go/src/github.com/irisnet/irishub/client/context/context.go:114 +0x309
github.com/irisnet/irishub/client/context.NewCLIContext(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/lhy/go/src/github.com/irisnet/irishub/client/context/context.go:73 +0x204
github.com/irisnet/irishub/lite.createHandler(0xc0007bb730, 0x5)
        /home/lhy/go/src/github.com/irisnet/irishub/lite/lcd.go:93 +0x82
github.com/irisnet/irishub/lite.ServeLCDStartCommand.func1(0xc0000aafc0, 0xc000a0de30, 0x0, 0x3, 0x0, 0x0)
        /home/lhy/go/src/github.com/irisnet/irishub/lite/lcd.go:40 +0x8e
github.com/irisnet/irishub/vendor/github.com/spf13/cobra.(*Command).execute(0xc0000aafc0, 0xc000a0dd70, 0x3, 0x3, 0xc0000aafc0, 0xc000a0dd70)
        /home/lhy/go/src/github.com/irisnet/irishub/vendor/github.com/spf13/cobra/command.go:698 +0x47a
github.com/irisnet/irishub/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1c9ea60, 0x24, 0xc000a0ee06, 0xf05a3b)
        /home/lhy/go/src/github.com/irisnet/irishub/vendor/github.com/spf13/cobra/command.go:783 +0x2dc
github.com/irisnet/irishub/vendor/github.com/spf13/cobra.(*Command).Execute(0x1c9ea60, 0x1, 0xc00017c8f8)
        /home/lhy/go/src/github.com/irisnet/irishub/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/libs/cli.Executor.Execute(0x1c9ea60, 0x1291d30, 0x7, 0xc000a10e20)
        /home/lhy/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/libs/cli/setup.go:89 +0x4e
main.main()
        /home/lhy/go/src/github.com/irisnet/irishub/cmd/irislcd/main.go:32 +0xf0
```
I think `resource temporarily unavailable` can remind users if they have started other irislcd processes which use the same home directory.
