### ISSUE TITLE
Exempt service providers from timeout slash in the profiling mode

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1274]
Technically, the profiler can fully occupy the service resources without any service-fee.

So we need decide ,  should we punish the Service Provider if he doesn't response profiling invocation?

**Comment by haifengxi** [comment]
Good point, providers should be exempt from timeout slash under the profiling mode; however, the fact about providers not responding in time should still be recorded on the chain. @shilei-wang @chengwenxi

**Comment by shilei-wang** [comment]
Verify fixed
