### ISSUE TITLE
[p2] Bank send Tx failed in "Simulate Mode"

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1275]
**Describe the bug**
In bank send Tx ,  estimated gas < actual gas_used

**To Reproduce**
echo 1234567890 | iriscli bank send --amount=1003iris --to=faa1264n55fg25z6czs43tk6j6rs3ravkz9x447gxx --from=v0 --fee=4iris --chain-id=shilei-qa --gas="simulate" --commit

stimated gas = 6186
simulation code = 0
simulation log = Msg 0:
simulation gas wanted = 1
simulation gas used = 4124
simulation fee amount = 0
simulation fee denom =
simulation tag action = send
simulation tag sender = faa18mw45whv79taelrgwt7cmfc2l0zwf5xmt0m00s
simulation tag recipient = faa1264n55fg25z6czs43tk6j6rs3ravkz9x447gxx
ERROR: {"codespace":"sdk","code":12,"message":"out of gas in location: setCoins"}

**Comment by HaoyangLiu** [comment]
This has been fixed by https://github.com/irisnet/irishub/pull/1273
