### ISSUE TITLE
Genesis file gentx json object key is using capital letters

### ISSUE THREAD

**Issue by kwunyeung** [irisnet/irishub#1277]
In the genesis file, all object keys are expected to be in lower cases but `Description` and `Commission` in `stake` object of `gentxs` are with first capital letters. This should be updated to keep consistency.

**Comment by wukongcheng** [comment]
If we make this change now, the previous submitted gentx.json will be broken.

**Comment by kwunyeung** [comment]
I know as all txs have to be signed again. That's why I only submitted the issue here. It can be done in later version. The current problem is not a big issue but not convenient in certain level of development.

**Comment by haifengxi** [comment]
The easiest way to fix this is to wait for the "opportunity" of a class4 upgrade (i.e., restarting a new blockchain), which itself is not desirable.  So let's keep this in the "wish list" for now.

**Comment by haifengxi** [comment]
The issue will be automatically fixed in v1.0
