### ISSUE TITLE
Add websocket proxy to LCD

### ISSUE THREAD

**Issue by HaoyangLiu** [irisnet/irishub#1280]
Now only irishub full nodes have websocket rpc, lcd doesn't have any websocket APIs. As a result, clients can't subscribe event from LCD. We plan to make LCD support websocket.

**Comment by haifengxi** [comment]
The current plan is to use language specific client-side library (sdk), JavaScript being the first target, to encapsulate interactions with back-end LCD and RPC (including websocket based subscriptions).  Closing for now.
