### ISSUE TITLE
[p3] Default gas isn't enough to support Redelegate Tx

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1282]
iriscli stake redelegate --address-validator-source=fva157jcm5nw8csql4tus96xc93xg22qgj84vgp3gt --address-validator-dest=fva17vuans09hv208vjms5fl7dekrd92gl9mtprl9a --shares-amount=3 --fee=0.004iris --from=v0 --chain-id=shilei-qa --commit
ERROR: {"codespace":"sdk","code":12,"message":"out of gas in location: WritePerByte"}

gas used > 20000

**Comment by haifengxi** [comment]
I noticed the issue too, should probably set default gas to 30000. @wukongcheng
