### ISSUE TITLE
[p2] Duplicate coin-flow logs found in command--"distribution withdraw-rewards --is-validator=true"

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1289]
**Describe the bug**
Duplicate coin-flow logs found

**To Reproduce**
echo 1234567890 | iriscli distribution withdraw-rewards --is-validator=true --from=v0 --fee=0.004iris --chain-id=shilei-qa

  "coin_flow": [
    **"fva1ryjqwj5gnxc2wz90fukcxcat5k0twrz8hpjdfs::faa1ryjqwj5gnxc2wz90fukcxcat5k0twrz8zscz5h::1384916400000000iris-atto::ValidatorReward::2019-02-22 09:18:18.821027516 +0000 UTC",
    "fva1ryjqwj5gnxc2wz90fukcxcat5k0twrz8hpjdfs::faa1ryjqwj5gnxc2wz90fukcxcat5k0twrz8zscz5h::1384916400000000iris-atto::ValidatorReward::2019-02-22 09:18:18.821027516 +0000 UTC",**
    "fva1ryjqwj5gnxc2wz90fukcxcat5k0twrz8hpjdfs::faa1ryjqwj5gnxc2wz90fukcxcat5k0twrz8zscz5h::223614314579600000000iris-atto::ValidatorCommission::2019-02-22 09:18:18.821027516 +0000 UTC"
  ]

**Comment by HaoyangLiu** [comment]
Fixed in https://github.com/irisnet/irishub/pull/1288
