### ISSUE TITLE
lcd get_stake_validators Interface problem

### ISSUE THREAD

**Issue by huang0227** [irisnet/irishub#1330]
The LCD interface get_stakeholder validators can retrieve fewer results.  now Four were found, and six were expected.

**Comment by wukongcheng** [comment]
Could you please describe the problem clearly？And give us the steps to reproduce this issue. Thanks for reporting.

**Comment by huang0227** [comment]
The result of using the iriscli stake validators command line is not consistent with the LCD get_stakeholder validators. The LCD only queries the maximum number of validators configured in genesis, not all the validators

**Comment by wukongcheng** [comment]
I didn't get which lcd api you mean. Are you talking about this api `/stake/validators` ？
