### ISSUE TITLE
[p2] "Memory pool block" occurs in full-node whose persistent peer's number is 1

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1365]
Precondition: the full-node has very few persistent peers (may be 1)

It's noticed that the full-node's Memory pool was blocked after a large number of transactions were broadcasted by it.

As long as it happened , no transactions can be broadcasted any more, we have to restart the node to solve it!

**Comment by wukongcheng** [comment]
Make sure the connection with the only peer is still alive.

**Comment by chengwenxi** [comment]
One node receives a transaction message when the node has just started, `checkState.ctx.ChainID` is empty, which will cause the node to verify the transaction failed.

If Node A only connects to Node B, this problem occurs when we send a transaction to Node A and restart Node B.

---
Why `checkState.ctx.ChainID` is empty?

The checkState chainID can only be set/reset in `initChain` and `app.commit`, so if a node is restarted, it must wait for a block to be commited and the checkState chainID is not empty.

**Comment by shilei-wang** [comment]
cannot reproduce
