### ISSUE TITLE
[p2][LCD] The TX signed by "POST /tx/sign" cannot be broadcast using "POST /tx/broadcast" (Interface incompatible)

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1385]
**To Reproduce**
1. Use "POST /tx/sign" to sign a TX
2. Copy the response Json to "POST /tx/broadcast"
3. Broadcast the TX
4. return error:
{"codespace":"sdk","code":1,"message":"Tx.GetMsgs() must return at least one message in list"}
5. The "denom" in response Json of  "POST /tx/sign" is also incorrect
{"codespace":"sdk","code":19,"message":"no native fee token, expected native token is iris-atto"}

Currect version：
v0.13.1

**Comment by chengwenxi** [comment]
I fix it at https://github.com/irisnet/irishub/pull/1446,  but I don't think it's necessary. 

We place the tx body inside `tx` in the json data for /tx/sign and /tx/broadcast, it seems better to use the same format.

**Comment by haifengxi** [comment]
Let's not fix it then.
