### ISSUE TITLE
通过钱包解委托和通过命令行解委托，txs接口返回的数量，单位不一致

### ISSUE THREAD

**Issue by wetezos** [irisnet/irishub#1394]
**Describe the bug**
如题，
通过命令行解委托，txs接口返回的shares_amount 是乘以10^18 
而通过钱包（lcd接口）解委托，shares_amount 为 原值。

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by chengwenxi** [comment]
We'll do that in the next version, Ref: https://github.com/irisnet/irishub/issues/1375

**Comment by haifengxi** [comment]
Replaced by #1375
