### ISSUE TITLE
lcd接口unbonding_delegations返回的解委托数量不正确

### ISSUE THREAD

**Issue by wetezos** [irisnet/irishub#1399]
**Describe the bug**
如题，我解委托了5个iris，但通过lcd 查看的数量不准确。
**To Reproduce**
1、通过钱包发起解委托
2、通过 hash 可以看到 解委托数量（E892CFB4D491EAF8998B63C9AF10A4EEF027E4AEDD620A08E24690B95B43FF04）
3、通过lcd解委托接口，查看数量不准确。（/stake/delegators/{delegatorAddr}/unbonding_delegations）

**Comment by chengwenxi** [comment]
The `shares_amount/delegate tokens` is not always equery 1.

**Comment by shilei-wang** [comment]
这里其实是一个单位的问题， 返回的时候单位问题  ：

比如我解委托 1iris.

通过 iriscli tendermint tx 查询，结果是
 "shares_amount": "1000000000000000000.0000000000"   这里的单位是iris-atto

通过 iriscli stake unbonding-delegations 查询，结果是
"initial_balance": "1iris",  单位是iris


1iris = 1*10^18iris-atto, 你实际解委托是的5iris-atto

shares和实际的iris有时候并不是1:1的关系

**Comment by haifengxi** [comment]
This is really not a bug per se.  Will improve output for `iriscli tendermint tx` command though.
