### ISSUE TITLE
Fix broadcastTxRoutine leak

### ISSUE THREAD

**Issue by haifengxi** [irisnet/irishub#1408]
[mempool]

Although we have addressed this in https://github.com/irisnet/irishub/issues/1202, there is still some broadcastTxRoutine leakage that needs to be fixed.

Ref: https://github.com/tendermint/tendermint/issues/3306
Cherry pick: https://github.com/tendermint/tendermint/pull/3478

**Comment by HaoyangLiu** [comment]
Good catch！
