### ISSUE TITLE
建议放开解委托次数限制

### ISSUE THREAD

**Issue by wetezos** [irisnet/irishub#1410]
**Is your feature request related to a problem? Please describe.**
目前有很多用户给我们反馈，第一次解委托，是做试验性操作，然后想进一步解委托，发现不能继续操作了，需要等第一次解委托成功后（等21天），在进行下一次解委托（需要在等21天），等待时间过长。
**Describe the solution you'd like**
因此，是否可以考虑把解委托的次数，适当放开，增加到5次左右呢？

**Describe alternatives you've considered**

**Additional context**

**Comment by haifengxi** [comment]
We'll evaluate this request.  To mitigate this problem in the short term, you can ask your users to distribute their delegations across multiple validators instead of concentrating them on one or two validators.

**Comment by kwunyeung** [comment]
I think the limitation on unbonding service as big consideration to delegators. It's affecting the security of the network and delegators should consider it deeply before taking the action. If they would like to test, they should do it on testnet but not on mainnet for such testing action. I would prefer keep the current limitation but suggest explorer/wallets to give better warning before the delegators unbond.
