### ISSUE TITLE
[p3] "Keys" module fail to support "json-indent" output

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1411]
**To Reproduce**
iriscli keys list -o=json --indent
ERROR: unknown flag: --indent

The output of json format is unreadable.
for example:
root@ubuntu16:~# iriscli keys list -o=json
[{"name":"node0","type":"local","address":"faa1ugvhffeqfsps8huydgn9ajtgxh8kgszuduukrv","pub_key":"fap1addwnpepqdzhruaddjnd030kzunl5qkch337h8nxyy6a2rgkkh2vevksyqle5vt9xnn"},{"name":"v0","type":"local","address":"faa1ugvhffeqfsps8huydgn9ajtgxh8kgszuduukrv","pub_key":"fap1addwnpepqdzhruaddjnd030kzunl5qkch337h8nxyy6a2rgkkh2vevksyqle5vt9xnn"}]

Currect version：
v0.14.0

**Comment by haifengxi** [comment]
Close this issue after confirming the bug fix in the next round of QA test. @shilei-wang

**Comment by shilei-wang** [comment]
confirmed
