### ISSUE TITLE
[p3] The query outputs of "stake redelegation" and "stake unbonding-delegation" are inconsistent

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1412]
**To Reproduce**
It only happens while unbonding/redelating period is passed.
The query outputs of "stake redelegation" and "stake unbonding-delegation" are inconsistent.

--------------------
iriscli stake unbonding-delegation --address-delegator=faa** --address-validator=fva**
output:
ERROR: {"codespace":"stake","code":102,"message":"no unbonding delegation found"}

iriscli stake redelegation --address-validator-source=fva** --address-validator-dest=fva** --address-delegator=faa**
output:
ERROR: UnmarshalBinaryLengthPrefixed cannot decode empty bytes

Currect version：
v0.14.0

**Comment by haifengxi** [comment]
Close this issue after confirming the bug fix in the next round of QA test. @shilei-wang

**Comment by shilei-wang** [comment]
confirmed
