### ISSUE TITLE
[p3] Several query commands in "distribution" fail to support "normal" output, all the returns of these commands are "json" format.

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1416]
These commands are :
iriscli distribution delegator-distr-info
iriscli distribution delegation-distr-info
iriscli distribution validator-distr-info

-----------------------

**To Reproduce**

for example, in non-json mode:

iriscli distribution delegator-distr-info faa1ugvhffeqfsps8huydgn9ajtgxh8kgszuduukrv  --chain-id=shilei-qa
[
  {
    "delegator_addr": "faa1ugvhffeqfsps8huydgn9ajtgxh8kgszuduukrv",
    "val_operator_addr": "fva1ugvhffeqfsps8huydgn9ajtgxh8kgszucdke7t",
    "del_pool_withdrawal_height": "1576"
  }
]

Currect version：
v0.14.0

**Comment by chengwenxi** [comment]
These three apis don't seem to make much sense, so should we consider removing them? @haifengxi

**Comment by haifengxi** [comment]
Let's drop these three subcommands @chengwenxi
