### ISSUE TITLE
Allow users to generate send tx offline

### ISSUE THREAD

**Issue by summerxue1992** [irisnet/irishub#1443]
You cannot build a transaction without a signed part on a node that is completely offline.When I build a transaction without a signature on a node without synchronized data,it prompts me to take the --node parameter.Connect to another node remotely to build the transaction,I think this goes against the definition of an offline signature.

**Comment by chengwenxi** [comment]
Thank you for rising this issue.

**Comment by haifengxi** [comment]
You have to be online to generate a tx, but can stay offline when signing it -- which is perfectly fine and safe.  @summerxue1992

**Comment by chengwenxi** [comment]
This error occurred when creating transaction, will fix it.
