### ISSUE TITLE
Candidates will also have blockchain rewards 

### ISSUE THREAD

**Issue by huang0227** [irisnet/irishub#1457]
**Describe the bug**
1:Candidates will also have validator rewards .
2:when delegator delegate candidate,delegator also have rewards.

**To Reproduce**
1. become a validator.
2.Because it's less than the top 100, become a candadte and always on line.
3. delegator delegate candidate
4.Over time, returns validator rewards and delegator rewards increase. but Very little.

**Comment by chengwenxi** [comment]
This is a known issue.

Candidate cann't get blockchain rewards, but a dalegator can withdraw rewards from a candidate   again and again if there are some rewards in the candidate.
