### ISSUE TITLE
KMS protocol error

### ISSUE THREAD

**Issue by mdyring** [irisnet/irishub#1461]
Referencing https://github.com/tendermint/kms/issues/255 as it is unclear where problem lies.

**Comment by mdyring** [comment]
zaki: "This sounds like a secret connection needing to re-key and the lack of auto restart on the Tendermint side causing a failure"

https://twitter.com/zmanian/status/1131821126542192640

**Comment by haifengxi** [comment]
#1405 has been fixed in irishub v0.14.  Please wait for a couple days and we'll release v0.14.0 in a week. @mdyring
