### ISSUE TITLE
[p3] The query outputs of "iriscli bank account" and "/bank/accounts/{address}" are inconsistent

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1486]
**To Reproduce**
Output format is different :

"iriscli bank account" :
--------------------
  {
  "type": "irishub/bank/Account",
  "value": {
    "address":"-",

>     "coins": [
>       {
>         "denom": "iris-atto",
>         "amount": "1999933819281858309034979833"
>       }
>     ],

  "public_key": {
      "type":"-",
      "value": "-",
    },
    "account_number":"-",
    "sequence":"-"
  }
}

/bank/accounts/{address}
--------------------
{
  "address":"-",

>   "coins": [
>     "1999933819.281858309034979833iris"
>   ],

  "public_key": {
    "type": "-",
    "value": "-"
  },
  "account_number":"-",
  "sequence": "-"
}

Currect version：
v0.14.0

**Comment by haifengxi** [comment]
PR the fix to release0.14 branch @chengwenxi

**Comment by shilei-wang** [comment]
confirm fixed
