### ISSUE TITLE
Transactions query endpoint does not return correct transactions.

### ISSUE THREAD

**Issue by rfunduk** [irisnet/irishub#1503]
**Describe the bug**
Querying for transactions using the `/txs` LCD endpoint does not seem to support all the expected tags.

**To Reproduce**
1. Find a send transaction's `sender` tag via the LCD. E.g. `curl -s "http://yournode:1317/txs?action=send" | jq '. | last | .result.Tags'`
2. `curl "http://yournode:1317/txs?action=send&sender=SENDERADDR"`
3. Observe that no transactions are returned.

**Expected behavior**
Specifying both `action` and `sender` tags should return the appropriate transactions.

**Comment by haifengxi** [comment]
In order to use tags as query parameters, you need to turn on indexing for those tags in `config/config.toml`, e.g., `index_tags = "action,sender"`.

The more indices you turn on, the more disk space will be used.  @rfunduk

**Comment by rfunduk** [comment]
Well ok then! Perhaps an error message would be useful here: "cannot query unindexed tag 'x'" or similar.
