### ISSUE TITLE
Transactions LCD endpoint swagger documentation is incorrect.

### ISSUE THREAD

**Issue by rfunduk** [irisnet/irishub#1504]
**Describe the bug**
The swagger documentation for the `/txs` endpoint is incorrect.

**To Reproduce**
1. Go to http://yournode:1317/swagger-ui/
2. Find `/txs` endpoint in the list and expand it.
3. Observe that the documentation instructs you to use a `tags` query parameter which has this description:

    > Query transactions with tags such as action=send, sender=faa1ljemm0yznz58qxxs8xyak7fashcfxf5lssn6jm and recipient=faa1252wk9khhks260shar975x7fswqxltc8tgvtl8, just input {"action":"send","sender":"faa1ljemm0yznz58qxxs8xyak7fashcfxf5lssn6jm","recipient":"faa1252wk9khhks260shar975x7fswqxltc8tgvtl8"}

    But this is not correct, from reading [the code](https://github.com/irisnet/irishub/blob/313b745eec5ca9c97fd6c608a22b1db2934bf9d5/client/tendermint/tx/searchtx.go#L162-L173), it's evident you're supposed to simply pass the tags as plain query parameters.

**Expected behavior**
Documentation is correct and matches LCD behaviour.

**Screenshots**
![image](https://user-images.githubusercontent.com/6437/58645121-b6037880-82d0-11e9-8c22-ce511dd3694f.png)

**Comment by haifengxi** [comment]
The swagger doc talks about how to specify parameters **for the swagger tool**, which in turn generates the correct GET URL with corresponding query parameters.  So the swagger doc is OK. @rfunduk

**Comment by rfunduk** [comment]
Hm ok, can you by chance point me to where I should be getting documentation for LCD endpoints?

**Comment by haifengxi** [comment]
Right now, the swagger UI does serve as documentation for LCD endpoints, which follow the RESTful design very closely.  For GET endpoints, by clicking `Try it out` and `Execute`, you can see the Request URL (with query parameters) and Response body.

I feel that you are looking for something like MkDocs powered API site, which unfortunately we don't provide yet.
