### ISSUE TITLE
There was no clearance of upgrade signals used in the tally endblocker

### ISSUE THREAD

**Issue by anagnoresis** [irisnet/irishub#1513]
Signals were left behind and remained uncleared in the upgrade store in each tally endblocker. As the app version number grew, validator signals of older version apps got increased in pace. Need to add a signal cleaner `uk.ClearSignals(ctx, upgradeConfig.ProtocolDef.Version)` before `uk.protocolKeeper.ClearUpgradeConfig(ctx)`.

**Comment by haifengxi** [comment]
Thanks for submitting the issue.  We have sort of left the signals in the store on purpose, for two reasons: 1) each set of signals represent the complete history of a corresponding upgrade, and could be used for various data mining purposes in the future; 2) they really don't take up that much space in the application db anyway. @anagnoresis

**Comment by haifengxi** [comment]
However, we really appreciate your reaching out and reporting the issue to us, and hope to see you often at our repo and projects.
