### ISSUE TITLE
[p1] Voting tally fails to cover the case where a voter is validator and delegator at the same time

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1526]
**Describe the bug**
This bug may involve Cosmos.

Cause of this bug：
```java
foreach [voters] {
      if (voter == validator) { do some statistics }
      else if (voter == delegator) { do some statistics }

      /*
       Code logic fail to cover the following path  ：
       if (voter == validator &&  voter == delegator) { ???? }
      */
}
```

**To reproduce**
---------------
preconditions：
2 validators： v1 ， v2
v1 ---(self_bond 10iris)-----> validator_1
v1 ---(delegate  1000iris)---> validator_2
v2 ---(self_bond 100iris)----> validator_2

submit a proposal
v1 vote Yes
v2 vote No

expected result：
    Yes = 1010
    No  = 100

actual result：
    Yes = 10
    No  = 1100（Obvious mistake！）

---------------
v0.15.0

**Comment by haifengxi** [comment]
Related: #1465

**Comment by shilei-wang** [comment]
verify fixed
