### ISSUE TITLE
[p2] Voting tally method leads to incorrect accuracy

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1527]
**To reproduce**
---------------
preconditions：
1 validator： v1
1 delegator： d1

v1 ---(self_bond 100iris)----> validator_1
d1 ---(delegate  50iris)-----> validator_1

submit a proposal
d1 vote Yes

expected result：
    Yes = 50

actual result：
    Yes = 49.9999500

**Cause of this bug**
---------------
suppose d1 has 50 shares in validator_1:

Current computing method：
d1_VotingPower = (50 d1_shares)/(150 total_shares)  *   150 tokens = 49.9995

Actully, the following computing method may be better:
d1_VotingPower = (150 tokens)/(150 total_shares)  *  50 d1_shares  = 50

**Comment by haifengxi** [comment]
Related: #1465

**Comment by shilei-wang** [comment]
verify fixed
