### ISSUE TITLE
[p3] The default proposal_type in swagger:/gov/proposals should be PlainText

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1528]
Edit Value
Model
{
  "base_tx": {
    "name": "faucet",
    "password": "1234567890",
    "chain_id": "irishub-test",
    "account_number": "0",
    "sequence": "0",
    "gas": "20000",
    "fee": "0.4iris",
    "gas_adjustment": "1.2"
  },
  "title": "string",
  "description": "string",
  "proposal_type": "Text",

>   should  update to -->   "proposal_type": "PlainText",
    

  "proposer": "faa1r93p0tpdlxgpac744rghvj9kqntvd54lc3msk2",
  "initial_deposit": "10iris"

>   should  update to 1000iris -->  "initial_deposit": "1000iris"

}

**Comment by haifengxi** [comment]
Related: #1462

**Comment by shilei-wang** [comment]
verify fixed
