### ISSUE TITLE
moniker change to "server name" if don't specific --moniker on edit-valdidator

### ISSUE THREAD

**Issue by liangping** [irisnet/irishub#1536]
**Describe the bug**
I update identity for my validator,  but moniker change to server name . it should be keep as same as it was.

**To Reproduce**
`iriscli stake edit-validator --from ping --identity 6EA723DA332200B2 --website ping.pub  --trust-node --chain-id nyancat --fee 0.4iris`

```
Sync committed (tx hash: 443B7D1AC7E98B7E4925FEE5E0ADC01CAA8DF129C52656F173B3E28C25973176, response:
 {
   "code": 0,
   "data": "",
   "log": "",
   "info": "",
   "gas_wanted": 0,
   "gas_used": 0,
   "codespace": ""
 })
```

**Expected behavior**
keep my old moniker, only update identity for my validator.

**Comment by zhangyelong** [comment]
Duplicated: #348
