### ISSUE TITLE
Deposit end time looks incorrect when a proposal enters the voting stage early

### ISSUE THREAD

**Issue by huang0227** [irisnet/irishub#1546]
The deposit_end_time would be the same as voting_end_time when the proposal is made directly into the voting stage.
1:submit-proposal 's deposit is enough。
2：proposal' status is voting.
3:Query this  proposal

**Comment by huang0227** [comment]
![image](https://user-images.githubusercontent.com/14272473/59181082-14660c00-8b99-11e9-8942-f73b7d21e99e.png)

**Comment by zhiqiang-bianjie** [comment]
@huang0227 “deposit_end_time” refers to the delegate deadline, not the delegate end time. When the proposal is directly from the submission to the voting stage, if the delegate period is the same as the voting period, then “deposit_end_time” is the same as “voting_end_time”.

**Comment by haifengxi** [comment]
Closing for now...
