### ISSUE TITLE
Add network type in iris/iriscli version message

### ISSUE THREAD

**Issue by zhangyelong** [irisnet/irishub#1552]
**Is your feature request related to a problem? Please describe.**
We can choose to compile source code for mainnet or testnet, but how do we know the network type of an  existing binary? We could add a new key via `iriscli keys add` then see the bech32 prefix of the address, it's a little confused but works. How about `iris`, it's much more complex, maybe we can init a local testnet by `iris testnet` command just to see the network type of a binary?

**Describe the solution you'd like**
Show the network type in version message
```bash
iris version
mainnet-0.15.0-dev-bf929e83-1
iriscli version
testnet-0.15.0-dev-bf929e83-1
```

**Comment by haifengxi** [comment]
[release]-[commit]-[protocol]-[network]
e.g., `0.15.0-dev-bf929e83-1-mainnet`
