### ISSUE TITLE
[p3] Resetting for an incorrect height should trigger proper error messages

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1553]
**To Reproduce**
1. Suppose the current height is 1000, and terminate the iris.
2. iris reset --height=2000 --home=****

output:
Reset app state to height 2000 successfully

**Expected behavior**
output:
Reset app state to latest height successfully

----------------
The same problem exists in " reset --height=0 "

**Comment by haifengxi** [comment]
Related: #1511

**Comment by shilei-wang** [comment]
confirm fixed
