### ISSUE TITLE
Print out progressing status when replaying large blocks

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1554]
**Describe the bug**
If the replay height is larger than 5000 blocks, the replay period is very long (maybe several minutes), we should give a appropriate prompt to user, not just suspend the program for several minutes.

**To Reproduce**
1. Suppose current height is 20000
2. iris reset --height=10000 --home=***
3. iris start --home=****
.... ....
The user has to wait a very long time without any prompt.
.... ....

**Comment by haifengxi** [comment]
Related: #1511
