### ISSUE TITLE
[p1] The cli export the snapshot at wrong height after resetting

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1556]
**Describe the bug**
After resetting the iris to a certain height and export the snapshot, it is expected that the snapshot is at the "reset" height. But in this case, the snapshot exported is at latest height , This is an obvious mistake.

**To Reproduce**
1. suppose current height is 20000
2. iris reset 10000 home=***
3. iris export home=***
The genesis exported is at height 20000

**Expected behavior**
The genesis exported is at height 10000

**Comment by haifengxi** [comment]
Related: #1511

**Comment by shilei-wang** [comment]
confirm fixed
