### ISSUE TITLE
[p3] Initiating a transaction with a multisig account returns unreadable error message

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1557]
**To Reproduce**
1. create a multi-sign account ==> x
2. iriscli bank send --amount=1iris --fee=0.004iris --commit --chain-id=shilei-qa --from=x --to=faa19m37j9rqhkzn8wsrhhrlas3p9tyj50pjgewgf3

Bytes to sign:
{"account_number":"2","chain_id":"shilei-qa","fee":{"amount":[{"amount":"4000000000000000","denom":"iris-atto"}],"gas":"50000"},"memo":"","msgs":[{"inputs":[{"address":"faa19m37j9rqhkzn8wsrhhrlas3p9tyj50pjgewgf3","coins":[{"amount":"1000000000000000000","denom":"iris-atto"}]}],"outputs":[{"address":"faa19m37j9rqhkzn8wsrhhrlas3p9tyj50pjgewgf3","coins":[{"amount":"1000000000000000000","denom":"iris-atto"}]}]}],"sequence":"0"}
Enter Amino-encoded signature:
ERROR: failed to decode signature: Not enough bytes to read in UnmarshalBinaryLengthPrefixed, want 49 more bytes but only have 10

**Comment by haifengxi** [comment]
Related: #1466

**Comment by shilei-wang** [comment]
Verify fixed
