### ISSUE TITLE
[p2] CommunityPool refactor breaks the query for community-tax

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1577]
**Describe the bug**
Maybe we should drop this command and use 'bank account' instead：
`iriscli bank account <commulity_tax_add>`

**To Reproduce**
`iriscli distribution community-tax`
ERROR: json: cannot unmarshal array into Go value of type map[string]json.RawMessage

version 0.15.0

**Comment by haifengxi** [comment]
Related: #1544

**Comment by haifengxi** [comment]
remove the query for community tax:
- lcd: `/distribution/community-tax`
- cli: `iriscli distribution community-tax`

**Comment by shilei-wang** [comment]
Verify fixed
