### ISSUE TITLE
[p0] Sending tokens directly to BurnedCoinsAccAddr breaks invariant check

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1578]
**Describe the bug**
We dont have this bug in mainnet. It is a new bug introduced by 'Refactor AccAddress'.

Maybe we should also pay attention to following command：
1.  iriscli distribution set-withdraw-addr <born_addr>
2. iriscli gov submit-proposal -type="TxTaxUsage" --usage="Distribute" --dest-address=<born_addr>
2. iriscli service withdraw-tax --dest-address=<born_addr>

**To Reproduce**
iriscli bank send --amount=100iris --fee=0.004iris --gas=200000 --commit --chain-id=shilei-qa --from=v0 --to=<born_addr>

CONSENSUS FAILURE!!!                         module=consensus err="invariant broken: loose token invariance:\n\tbank.LooseTokens: 1999999888000000000000000000\n\tsum of account tokens: 1999999788000000000000000000" stack="goroutine 29 [running]:\nruntime/debug.Stack(0x5aed5b8, 0x3ff0000000000000, 0x2)\n\t/usr/local/Cellar/go/1.12.5/libexec/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine.func2(0xc0009b4700, 0x4fc1420)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20190527110704-aff684d6c906/consensus/state.go:584 +0x12a\npanic(0x4cda1e0, 0xc0038091e0)\n\t/usr/local/Cellar/go/1.12.5/libexec/src/runtime/panic.go:522 +0x1b5\ngithub.com/irisnet/irishub/app/v1.(*ProtocolV1).assertRuntimeInvariants(0xc00094f800, 0x51777e0, 0xc002c252c0, 0xc003289340, 0x13)\n\t/Users/sherlock/go/src/github.com/irishub/app/v1/invariants.go:40 +0x710\ngithub.com/irisnet/irishub/app/v1.(*ProtocolV1).EndBlocker(0xc00094f800, 0x51777e0, 0xc002c252c0, 0xc003289340, 0x13, 0x39, 0x0, 0x0, 0x0, 0x0, ...)\n\t/Users/sherlock/go/src/github.com/irishub/app/v1/protocol_v1.go:356 +0x63e\ngithub.com/irisnet/irishub/app.(*BaseApp).EndBlock(0xc000208210, 0x39, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/Users/sherlock/go/src/github.com/irishub/app/baseapp.go:853 +0x793\ngithub.com/tendermint/tendermint/abci/client.(*localClient).EndBlockSync(0xc0000b0ba0, 0x39, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20190527110704-aff684d6c906/abci/client/local_client.go:239 +0xea\ngithub.com/tendermint/tendermint/proxy.(*appConnConsensus).EndBlockSync(0xc00006afe0, 0x39, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20190527110704-aff684d6c906/proxy/app_conn.go:77 +0x51\ngithub.com/tendermint/tendermint/state.execBlockOnProxyApp(0x5178420, 0xc0009dcc40, 0x5183280, 0xc00006afe0, 0xc00279cf00, 0xc002bfcba0, 0x518b8c0, 0xc0001d41a8, 0xa, 0xc00098b380, ...)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20190527110704-aff684d6c906/state/execution.go:282 +0x69f\ngithub.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc0009f0c40, 0x9, 0x1, 0xc00098b360, 0xa, 0xc00098b380, 0x9, 0x38, 0x2, 0xc00374cf20, ...)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20190527110704-aff684d6c906/state/execution.go:104 +0x195\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).finalizeCommit(0xc0009b4700, 0x39)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20190527110704-aff684d6c906/consensus/state.go:1305 +0x969\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).tryFinalizeCommit(0xc0009b4700, 0x39)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20190527110704-aff684d6c906/consensus/state.go:1236 +0x3e0\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit.func1(0xc0009b4700, 0x0, 0x39)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20190527110704-aff684d6c906/consensus/state.go:1182 +0x91\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit(0xc0009b4700, 0x39, 0x0)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20190527110704-aff684d6c906/consensus/state.go:1213 +0x61e\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).addVote(0xc0009b4700, 0xc003292dc0, 0x0, 0x0, 0xc0008adc20, 0xc0009fc000, 0xc00234bae0)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20190527110704-aff684d6c906/consensus/state.go:1638 +0xb43\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).tryAddVote(0xc0009b4700, 0xc003292dc0, 0x0, 0x0, 0xc000000008, 0xc00234bb90, 0x402f051)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20190527110704-aff684d6c906/consensus/state.go:1484 +0x5c\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).handleMsg(0xc0009b4700, 0x5159e80, 0xc0029da540, 0x0, 0x0)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20190527110704-aff684d6c906/consensus/state.go:663 +0x6cc\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine(0xc0009b4700, 0x0)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20190527110704-aff684d6c906/consensus/state.go:624 +0x544\ncreated by github.com/tendermint/tendermint/consensus.(*ConsensusState).OnStart\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.22.3-0.20190527110704-aff684d6c906/consensus/state.go:306 +0x12b\n"

------
v0.15.0

**Comment by haifengxi** [comment]
Related: #1544

**Comment by shilei-wang** [comment]
verify fixed
