### ISSUE TITLE
[p3] Asset issue-token fails to check the string length of "symbol-at-source"

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1619]
**Describe the bug**
According to the Spec, the length of "symbol-at-source" show be [3,8]
https://gitlab.bianjie.ai/irishub/internal-spec/blob/v0.15.0/asset/asset_ft.md

**To Reproduce**
Asset issue-token:
```
iriscli asset issue-token --symbol-at-source=a --symbol=abc --family=fungible --source=native  --name=asset-name --initial-supply=10000 --from=v0 --chain-id=shilei-qa --fee=0.6iris --commit
```

Query:
```
iriscli asset query-token abc
```

**Comment by zhangyelong** [comment]
`symbol-at-source` is ignored if source=native, because native token doesn't have a source chain

**Comment by shilei-wang** [comment]
confirm fixed
