### ISSUE TITLE
[p2] Burning native tokens will not decrease its "loose_tokens" at the same time

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1627]
**To Reproduce**
```
iriscli bank token-stats abc
```
TokenStats:
  Loose Tokens:  100abc-min
  Burned Tokens:  0abc-min
  Bonded Tokens:  

```
iriscli bank burn --amount=50abc --fee=0.004iris --commit --chain-id=shilei-qa --from=v0
```
**Query again**
```
iriscli bank token-stats abc
```
TokenStats:
  Loose Tokens:  100abc-min
  Burned Tokens:  50abc-min
  Bonded Tokens:

**Comment by haifengxi** [comment]
Related: #1603
