### ISSUE TITLE
[p1] "GET /asset/tokens" doesn't work due to the bug-fix of #1625

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1656]
**Describe the bug**
Currently, the query of "GET /asset/tokens" doesn't work. This bug is introduced by the bug-fix of https://github.com/irisnet/irishub/issues/1625 .

**Comment by zhangyelong** [comment]
Fixed in this pr: #1640

**Comment by shilei-wang** [comment]
confirm fixed
