### ISSUE TITLE
End-time is wrong in the redelegate query api

### ISSUE THREAD

**Issue by huang0227** [irisnet/irishub#1698]
In the hash details of the redelegate transaction, the time of the lockup period is shown as 0001/01/01, there is a problem.
1:from jailed Validator  redelegate active validator,
2:query tx lcd , this redelegate transaction's end time is wrong .
ex:
{
  "hash": "638087FCF75591CBBCE899F9A16CE36E4D277AA8BACD320009CE0B1DB4FE7E64",
  "height": "1320993",
  "tx": {
    "type": "irishub/bank/StdTx",
    "value": {
      "msg": [
        {
          "type": "irishub/stake/BeginRedelegate",
          "value": {
            "delegator_addr": "faa1eqvkfthtrr93g4p9qspp54w6dtjtrn279vcmpn",
            "validator_src_addr": "fva1mnvpydvgsevvrtlwxfkkujkr3d74p08da5fchj",
            "validator_dst_addr": "fva10jv6pkdtjc39pwpjxnurqend0p09gphlyhzmel",
            "shares_amount": "100000000000000000.0000000000"
          }
        }
      ],
      "fee": {
        "amount": [
          {
            "denom": "iris-atto",
            "amount": "600000000000000000"
          }
        ],
        "gas": "100000"
      },
      "signatures": [
        {
          "pub_key": {
            "type": "tendermint/PubKeySecp256k1",
            "value": "A4vkU5eF8GIaGQZustpFwR3MX8z/XVjonGcLuA0lHMG3"
          },
          "signature": "zpoA66/2gjCz5FZRKWUK+IqaFCqNazFGE/hhlTX06WVwjQto0eVLUz/jhK6PWOmam1hrVIS0CH/Sz1bfI9P9Cw==",
          "account_number": "5",
          "sequence": "230"
        }
      ],
      "memo": ""
    }
  },
  "result": {
    "Code": 0,
    "Data": "CwiAkrjDmP7///8B",
    "Log": "Msg 0: ",
    "Info": "",
    "GasWanted": "100000",
    "GasUsed": "46483",
    "Tags": [
      {
        "key": "action",
        "value": "begin_redelegate"
      },
      {
        "key": "delegator",
        "value": "faa1eqvkfthtrr93g4p9qspp54w6dtjtrn279vcmpn"
      },
      {
        "key": "source-validator",
        "value": "fva1mnvpydvgsevvrtlwxfkkujkr3d74p08da5fchj"
      },
      {
        "key": "destination-validator",
        "value": "fva10jv6pkdtjc39pwpjxnurqend0p09gphlyhzmel"
      },
      {
        "key": "end-time",
        "value": "0001-01-01 00:00:00 +0000 UTC"
      },
      {
        "key": "balance",
        "value": "100000000000000000iris-atto"
      },
      {
        "key": "shares-src",
        "value": "100000000000000000.0000000000"
      },
      {
        "key": "shares-dst",
        "value": "100000000000000000.0000000000"
      }
    ],
    "Codespace": "",
    "XXX_NoUnkeyedLiteral": {},
    "XXX_unrecognized": null,
    "XXX_sizecache": 0
  },
  "coin_flow": [
    "fva1mnvpydvgsevvrtlwxfkkujkr3d74p08da5fchj::faa1mnvpydvgsevvrtlwxfkkujkr3d74p08dg9rh24::24541316083712222358iris-atto::ValidatorReward::::2019-07-01 06:13:05.915055981 +0000 UTC",
    "fva1mnvpydvgsevvrtlwxfkkujkr3d74p08da5fchj::faa1eqvkfthtrr93g4p9qspp54w6dtjtrn279vcmpn::150084378037209612iris-atto::DelegatorReward::::2019-07-01 06:13:05.915055981 +0000 UTC",
    "fva10jv6pkdtjc39pwpjxnurqend0p09gphlyhzmel::faa10jv6pkdtjc39pwpjxnurqend0p09gphl3xg5yc::39167173723350846672iris-atto::ValidatorReward::::2019-07-01 06:13:05.915055981 +0000 UTC",
    "fva10jv6pkdtjc39pwpjxnurqend0p09gphlyhzmel::faa1eqvkfthtrr93g4p9qspp54w6dtjtrn279vcmpn::5690114498362006112415iris-atto::DelegatorReward::::2019-07-01 06:13:05.915055981 +0000 UTC"
  ]
}

**Comment by haifengxi** [comment]
Fixed: #1383
