### ISSUE TITLE
[p2] "iriscli stake pool" shows confusing result

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1724]
The decimal contains 28 zeros  ???

iriscli stake pool
Pool:
  Loose Tokens:   1999999900.0000000000000000000000000000         <=== contains 28 zeros
  Bonded Tokens:  100.0000000000000000000000000000
  Token Supply:   2000000000.0000000000000000000000000000
  Bonded Ratio:   0.0000000500000000000000000000

Maybe we could drop this query command, cause we have the folowing instead :

-------
iriscli bank token-stats iris
TokenStats:
  Loose Tokens:   1999999900iris
  Bonded Tokens:  100iris
  Burned Tokens:  0iris
  Total Supply:   2000000000iris

**Comment by haifengxi** [comment]
I think we can drop `iriscli stake pool`

**Comment by chengwenxi** [comment]
/stake/pool is used by some wallets, so retains it.

**Comment by shilei-wang** [comment]
confirm fixed
