### ISSUE TITLE
[p2] Flag Symbol-Min-Alias is useless, it would not be used to send tokens

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1725]
**Describe the bug**
If specify Symbol-Min-Alias="btc-atto" when issuing btc token.

Only btc-min can be used to send tokens, but not btc-atto.

Maybe we could drop this flag , since it is useless and confused.

**Comment by secret2830** [comment]
SymbolMinAlias is used for UI display purpose.

**Comment by shilei-wang** [comment]
confirm fixed
