### ISSUE TITLE
List all actions for txs on LCD

### ISSUE THREAD

**Issue by liangping** [irisnet/irishub#1762]
we can query txs by following url. 
http://host:1317/txs?action=burn/send 

However, we don't know what actions are available. 
So, can you list all actions in document or swagger

**Comment by chengwenxi** [comment]
@liangping You can find the list of all actions here:
https://github.com/irisnet/irishub/blob/master/docs/cli-client/tendermint/txs.md#actions-list

**Comment by liangping** [comment]
@chengwenxi thanks
