### ISSUE TITLE
Optimize error messages

### ISSUE THREAD

**Issue by zhangyelong** [irisnet/irishub#1783]
**Is your feature request related to a problem? Please describe.**
Many error messages are confusing, almost every one asks what these mean and what they should do with them, e.g.
- ERROR: {"codespace":"sdk","code":19,"message":"no native fee token, expected native token is iris-atto"}
- ERROR: {"codespace":"sdk","code":17,"message":"equivalent gas price (1000000000000iris-atto) is less than threshold (6000000000000iris-atto)"}

**Describe the solution you'd like**
- ERROR: {"codespace":"sdk","code":19,"message":"`fee` is required to be specified with `iris`"}
- ERROR: {"codespace":"sdk","code":17,"message":"insufficient fee, fee = gasLimit * gasPrice(default 0.000006iris)"}

**Comment by shilei-wang** [comment]
confirm fixed
