### ISSUE TITLE
[p3] It's necessary to return the effective height for "rand/request-rand".

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1832]
**Describe the bug**
In the following case, we should tell user the exact effective height of random number instead of manual calculation （1366+10=1466）

----
echo 1234567890 | iriscli rand request-rand **--block-interval=10** --from=v0 --fee=0.004iris --commit --chain-id=shilei-qa
**Committed at block 1366** (tx hash: 36FC2AC3AA4B6DCA78914252B58BF96482E573A3D72B80205B988422D0F50A19, response: {****************}

（1366+10=1466）

iriscli rand query-queue --queue-height=1466

**Comment by chengwenxi** [comment]
fixed in https://github.com/irisnet/irishub/pull/1831

**Comment by shilei-wang** [comment]
confirm fixed
