### ISSUE TITLE
[p2] Should return correct error message when specify negative height for "queue-height"

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1834]
**To Reproduce**
```
iriscli rand query-queue --queue-height=-1234
```
---
Request:
  Height: 1804, Consumer: faa1d7fl9hd7pffscfjkqqrvkwqnkkc32fl5srra3a, TxHash: e60c6af6db913b4a0dc46cadb6ad2b62e0c344e5d18ca33346047492d2d976d2

**Comment by chengwenxi** [comment]
fixed in https://github.com/irisnet/irishub/pull/1831

**Comment by shilei-wang** [comment]
confirm fixed
