### ISSUE TITLE
Is there rpc

### ISSUE THREAD

**Issue by qiangshui** [irisnet/irishub#1847]

**Comment by zhangyelong** [comment]
Mainnet public rpc: http://seed-2.mainnet.irisnet.org:26657/
Mainnet public lcd: https://rpc.irisnet.org/swagger-ui/
Or you could use your own rpc and lcd after your node is fully synced:
rpc: http://localhost:26657
lcd: [docs](https://www.irisnet.org/docs/light-client/)
