### ISSUE TITLE
Hash lock based atomic swap

### ISSUE THREAD

**Issue by HaoyangLiu** [irisnet/irishub#1863]
Does irishub have a plan to support [Hash lock based atomic swap](https://github.com/binance-chain/BEPs/blob/master/BEP3.md). Comparing with IBC, it is much easier to implement and now more blockchain platforms can support it, including BTC and all other blockchain platforms which support smart contract.

**Comment by haifengxi** [comment]
We'll consider adding HTLC to v0.17

**Comment by haifengxi** [comment]
According to https://github.com/binance-chain/BEPs/blob/master/BEP3.md, you are actually doing cross-chain token "transfer" based on HTLC.  Right now our focus is on implementing the more general token (and data) transfer protocol - IBC.  So will have to put off HTLC until a little later.
