### ISSUE TITLE
Enable memo validation for "flagged" accounts

### ISSUE THREAD

**Issue by haifengxi** [irisnet/irishub#1867]
Ref:
https://github.com/cosmos/cosmos-sdk/issues/4523
https://github.com/binance-chain/BEPs/blob/master/BEP12.md

**Comment by HaoyangLiu** [comment]
related issue: https://github.com/irisnet/irishub/issues/1547
Binance Chain mainnet has already supported this feature: [Hubble Upgrade](https://community.binance.org/topic/1018/%E5%B8%81%E5%AE%89%E9%93%BE%E4%B8%BB%E7%BD%91-%E5%93%88%E5%8B%83-%E5%8D%87%E7%BA%A7%E5%85%AC%E5%91%8A)
