### ISSUE TITLE
[p1] Export Fuxi testnet for-zero-height panics 

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#1897]
**Describe the bug**
It is likely the panic causes by Stake or Distribution Txs.

After create some transactions(including Stake ,distribution)  in Fuxi testnet and export the blockchain for-zero-height, export panics and shows the following errors:

-----
panic: unexpected leftover validator pool coins: 7.0000000000

goroutine 1 [running]:
github.com/irisnet/irishub/app/v1.(*ProtocolV1).prepForZeroHeightGenesis(0xc00095a400, 0x51ca840, 0xc00091b320, 0xc0001f8940, 0x10)
	/Users/sherlock/go/src/github.com/irishub/app/v1/export.go:126 +0x15be
github.com/irisnet/irishub/app/v1.(*ProtocolV1).ExportAppStateAndValidators(0xc00095a400, 0x51ca840, 0xc00091b320, 0xc0001f8940, 0x10, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/sherlock/go/src/github.com/irishub/app/v1/export.go:29 +0x186c
github.com/irisnet/irishub/app.(*IrisApp).ExportAppStateAndValidators(0xc0000c0178, 0x3d01, 0xc000938240, 0x20, 0x20, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/sherlock/go/src/github.com/irishub/app/app.go:168 +0x180
main.exportAppStateAndTMValidators(0xc0001d3960, 0x51cb400, 0xc0009197c0, 0x51deea0, 0xc0000c0168, 0x0, 0x0, 0x3dd5, 0x1, 0xc00098b580, ...)
	/Users/sherlock/go/src/github.com/irishub/cmd/iris/main.go:108 +0x10d
github.com/irisnet/irishub/server.ExportCmd.func1(0xc000ae8900, 0xc0000dde90, 0x0, 0x3, 0x0, 0x0)
	/Users/sherlock/go/src/github.com/irishub/server/export.go:60 +0x44a
github.com/spf13/cobra.(*Command).execute(0xc000ae8900, 0xc0000dde00, 0x3, 0x3, 0xc000ae8900, 0xc0000dde00)
	/Users/sherlock/go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:698 +0x431
github.com/spf13/cobra.(*Command).ExecuteC(0xc000156b40, 0x2, 0xc0001d3c00, 0x4eaaa27)
	/Users/sherlock/go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:783 +0x2ca
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/sherlock/go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:736
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc000156b40, 0x50016d0, 0x4, 0xc000a06400)
	/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.31.0/libs/cli/setup.go:89 +0x3c
main.main()
	/Users/sherlock/go/src/github.com/irishub/cmd/iris/main.go:79 +0x5f3

**Comment by shilei-wang** [comment]
The bug was still observed in Coinswap

**Comment by chengwenxi** [comment]
> The bug was still observed in Coinswap

fixed it in https://github.com/irisnet/irishub/pull/1958

**Comment by shilei-wang** [comment]
confirm fixed
