### ISSUE TITLE
Wrong Block.Header.AppHash.

### ISSUE THREAD

**Issue by kirillbeldyaga** [irisnet/irishub#1907]
**Describe the bug**
I installed and initialized the iris and It crashed after three hours of syncing on block 52037.

I[2019-08-23|16:53:27.701] Executed block                               module=state height=52032 validTxs=0 invalidTxs=0
I[2019-08-23|16:53:27.766] Committed state                              module=state height=52032 txs=0 appHash=EBC69054C4E3F215490D650D8412C670AB95904D5A03DC19B3AA5580AABEC408
I[2019-08-23|16:53:27.923] Executed block                               module=state height=52033 validTxs=0 invalidTxs=0
I[2019-08-23|16:53:27.943] Committed state                              module=state height=52033 txs=0 appHash=4F9EFF48C3ADC6EC8E95CCF3EBF1C7594BA90FCBAEB1FE8005D35E8E22674FDD
I[2019-08-23|16:53:28.077] Executed block                               module=state height=52034 validTxs=0 invalidTxs=0
I[2019-08-23|16:53:28.114] Committed state                              module=state height=52034 txs=0 appHash=F602F7CE5480EE73C805EF95951124702D104B6B9200E555F9EEC5957E2107AF
I[2019-08-23|16:53:28.228] Executed block                               module=state height=52035 validTxs=0 invalidTxs=0
I[2019-08-23|16:53:28.244] Committed state                              module=state height=52035 txs=0 appHash=A1E040330BFE2809D9E3CC238D4F8BEA6EAE21AD1D70BB14813607D0F2F98F52
I[2019-08-23|16:53:28.411] Executed block                               module=state height=52036 validTxs=1 invalidTxs=0
I[2019-08-23|16:53:28.489] Committed state                              module=state height=52036 txs=1 appHash=9E1A74445C427656D159E74D9000EBCC8B0DD70C6F5DEEC35809BCE69A7BF45D
panic: Panicked questionably: Failed to process committed block (52037:79FCF046270668F330CE852EEE365606AF1EFE352D41F1B2201D0D2541947802): Wrong Block.Header.AppHash.  Expected 9E1A74445C427656D159E74D9000EBCC8B0DD70C6F5DEEC35809BCE69A7BF45D, got 25865C7ADCC4286C229736F28EFC6525DB6A4D5DE7EDA0E6B5C8923CB95931AE

goroutine 266 [running]:
github.com/tendermint/tendermint/libs/common.PanicQ(...)
	/home/kirillbeldyaga/go/pkg/mod/github.com/irisnet/tendermint@v0.31.0/libs/common/errors.go:245
github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).poolRoutine(0xc000b40b60)
	/home/kirillbeldyaga/go/pkg/mod/github.com/irisnet/tendermint@v0.31.0/blockchain/reactor.go:341 +0x196a
created by github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).OnStart
	/home/kirillbeldyaga/go/pkg/mod/github.com/irisnet/tendermint@v0.31.0/blockchain/reactor.go:118 +0x84

When i'm trying to start the full node again 
iris start
I[2019-08-23|17:26:48.983] Starting ABCI with Tendermint                module=main 
I[2019-08-23|17:26:49.250] ABCI Replay Blocks                           module=state appHeight=52036 storeHeight=52037 stateHeight=52036
I[2019-08-23|17:26:49.250] Replay last block using real app             module=state 
ERROR: Error during handshake: Error on replay: Wrong Block.Header.AppHash.  Expected 9E1A74445C427656D159E74D9000EBCC8B0DD70C6F5DEEC35809BCE69A7BF45D, got 25865C7ADCC4286C229736F28EFC6525DB6A4D5DE7EDA0E6B5C8923CB95931AE

**Additional info**
seeds = "174e6f483d925c3b5b70e2ced098916a8cf8fe4b@35.234.10.84:26656"
persistent_peers = "c87675bcaeb72a1f93dbf7d74f7b425690a994e3@34.80.202.172:26656"
chain-id nyancat-4
shasum -a 256 genesis.json 
aed9b92abf94079b6abe65b87558efeec9fa3cbc04b8f429604632f76efdc159  genesis.json
iris version
0.15.1-d2a77068-1-testnet

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 18.04

**Comment by chengwenxi** [comment]
Thanks for your report!
Nyancat-4 runs with 0.15.0-rc4, we adjusted the gas calculation in v0.15.1, so appHash has some conflicts.

**Comment by kirillbeldyaga** [comment]
@chengwenxi Thanks for your answer. Everything seems to work fine
