### ISSUE TITLE
API parameters naming is not standardized in iks

### ISSUE THREAD

**Issue by SegueII** [irisnet/irishub#1929]
### API parameters

There are two types of connectors: `_` and `-`
Password has two different names: `password` and `passphrase`

Example:

```
// BankSendBody contains the necessary data to make a send transaction
type BankSendBody struct {
	Sender        sdk.AccAddress `json:"sender"`
	Reciever      sdk.AccAddress `json:"reciever"`
	Amount        string         `json:"amount"`
	ChainID       string         `json:"chain-id"`
	Memo          string         `json:"memo,omitempty"`
	Fees          string         `json:"fees,omitempty"`
	GasAdjustment string         `json:"gas_adjustment,omitempty"`
}
```

```
// SignBody is the body for a sign request
type SignBody struct {
	Tx            json.RawMessage `json:"tx"`
	Name          string          `json:"name"`
	Passphrase    string          `json:"passphrase"`
	ChainID       string          `json:"chain_id"`
	AccountNumber string          `json:"account_number"`
	Sequence      string          `json:"sequence"`
}
```

Releated files:
[/irisnet/iks/api/keys](https://github.com/irisnet/iks/blob/master/api/keys.go)
[/irisnet/iks/api/result](https://github.com/irisnet/iks/blob/master/api/result.go)
[/irisnet/iks/api/send](https://github.com/irisnet/iks/blob/master/api/send.go)
[/irisnet/iks/api/sign](https://github.com/irisnet/iks/blob/master/api/sign.go)

**Comment by zhangyelong** [comment]
Shall we move `iks` issues to the [iks](https://github.com/irisnet/iks) repo? @haifengxi @chengwenxi

**Comment by chengwenxi** [comment]
> Shall we move `iks` issues to the [iks](https://github.com/irisnet/iks) repo? @haifengxi @chengwenxi

Yes, I think so too.

**Comment by haifengxi** [comment]
> Shall we move `iks` issues to the [iks](https://github.com/irisnet/iks) repo? @haifengxi @chengwenxi

Yes, we should do that.

**Comment by haifengxi** [comment]
Replaced by https://github.com/irisnet/iks/issues/4
