### ISSUE TITLE
contextKeyCheckValidNum make the apply block consume double time

### ISSUE THREAD

**Issue by wukongcheng** [irisnet/irishub#1950]
```
type valueCtx struct {
	Context
	key, val interface{}
}
```
The context under types/context is the golang valueCtx. And it only contain one key/val pair. So every `WithXXX` func in the types/context will new another valueCtx and refs the old one as the parent:
```
func WithValue(parent Context, key, val interface{}) Context {
	if key == nil {
		panic("nil key")
	}
	if !reflect.TypeOf(key).Comparable() {
		panic("key is not comparable")
	}
	return &valueCtx{parent, key, val}
}
```

When we read some key/value from context, we need to go through all the child-parent stack to find the one:
```
func (c *valueCtx) Value(key interface{}) interface{} {
	if c.key == key {
		return c.val
	}
	return c.Context.Value(key)
}
```
After we add the `proposalCensorship`, we call the `WithCheckValidNum` on context every runTx(). If the block has 5000 txs, it will make the context contain 5000+ key/val pairs. It means the depth of the context child-parent stack is 5000+, and the `chain-id`/`block height`/`logger` are on the bottom. So get value from the context will be much slow.

I try to remove the `WithCheckValidNum` and the `Block Processing Time` reduced from 6s to 3s.

**Comment by chengwenxi** [comment]
Thanks for your report, it's really a big vulnerability.  
I plan to use an interface instead of uint64 for CheckValidNum such as
```
type TxValidNum interface {
	Num() uint64
	Add()
}
```

and then we can add the count by
```
app.deliverState.ctx.CheckValidNum().Add()
```

Do you have any better suggestions?
