### ISSUE TITLE
Iris init created the folders .iris and .iricli in the same path where run the cmd.

### ISSUE THREAD

**Issue by iammelea** [irisnet/irishub#2025]
```Iris init ```
created the folders ```.iris``` and ```.iricli``` in the same path where run the cmd unless $HOME

**Comment by shilei-wang** [comment]
Thank you for reporting.

According to your description, I don't quite understand what you mean. I guess what you want to say is  -- "The default home folder(.iris) only created under $HOME after running `iris init`"

If you want to specify the "home" folder, you could add the flag `--home=/***/***` .
eg. `iris init --chain-id=***  --moniker=*** --home=/***/***`

OR

If you DON'T specify the "home" folder, the default "home" folder will be created under $HOME/.iris
eg. `iris init --chain-id=***  --moniker=***`

Besides， `iris init` won't create '.iriscli' folder,  only `iriscli *** ***` will.
