### ISSUE TITLE
The 0.15.3 version can not use iris --moniker? 

### ISSUE THREAD

**Issue by Victoryfan** [irisnet/irishub#2028]
![image](https://user-images.githubusercontent.com/25604389/66365382-5411f880-e9bf-11e9-9bb3-51fc42c23bd7.png)
![image](https://user-images.githubusercontent.com/25604389/66365874-1ada8800-e9c1-11e9-8b09-8350b853a19c.png)

**Comment by zhangyelong** [comment]
Hi, a sub-command is required, you can try `iris -h` for help.

**Comment by shilei-wang** [comment]
For example:
iris init --chain-id=nyancat  --moniker=v0 --home=/Users/sherlock/v0
iris start --home=/Users/sherlock/v0
