### ISSUE TITLE
[p2] Query the block （which height before snapshot）causes panic error message.

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#2064]
**Describe the bug**

`iriscli tendermint block 1 --chain-id=shilei-qa`

Create verifier failed: Commit: Response error: RPC error -32603 - Internal error: runtime error: invalid memory address or nil pointer dereference

----

E[2019-11-08|10:26:38.002] Panic in RPC HTTP handler                    module=rpc-server err="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 74228 [running]:\nruntime/debug.Stack(0xc0012614b0, 0x4d600e0, 0x5c0f390)\n\t/usr/local/Cellar/go/1.12.5/libexec/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/tendermint/tendermint/rpc/lib/server.RecoverAndLogHandler.func1.1(0xc00279bd00, 0x5285e60, 0xc00087aba0, 0xbf69527780130b00, 0x1a57454e3f0, 0x5c2ac00, 0xc002d35800)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.32.0/rpc/lib/server/http_server.go:133 +0x552\npanic(0x4d600e0, 0x5c0f390)\n\t/usr/local/Cellar/go/1.12.5/libexec/src/runtime/panic.go:522 +0x1b5\ngithub.com/tendermint/tendermint/rpc/core.Commit(0xc003f08990, 0x0, 0x0, 0x0)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.32.0/rpc/core/blocks.go:321 +0xb4\nreflect.Value.call(0x4d2db80, 0x503ea08, 0x13, 0x4ebfea8, 0x4, 0xc00279bd60, 0x1, 0x1, 0xc000101438, 0x0, ...)\n\t/usr/local/Cellar/go/1.12.5/libexec/src/reflect/value.go:447 +0x461\nreflect.Value.Call(0x4d2db80, 0x503ea08, 0x13, 0xc00279bd60, 0x1, 0x1, 0xc00279bd60, 0x1, 0x1)\n\t/usr/local/Cellar/go/1.12.5/libexec/src/reflect/value.go:308 +0xa4\ngithub.com/tendermint/tendermint/rpc/lib/server.makeJSONRPCHandler.func1(0x52800a0, 0xc00279bd00, 0xc002d35800)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.32.0/rpc/lib/server/handlers.go:145 +0x407\ngithub.com/tendermint/tendermint/rpc/lib/server.handleInvalidJSONRPCPaths.func1(0x52800a0, 0xc00279bd00, 0xc002d35800)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.32.0/rpc/lib/server/handlers.go:165 +0x9c\nnet/http.HandlerFunc.ServeHTTP(0xc0009a53c0, 0x52800a0, 0xc00279bd00, 0xc002d35800)\n\t/usr/local/Cellar/go/1.12.5/libexec/src/net/http/server.go:1995 +0x44\nnet/http.(*ServeMux).ServeHTTP(0xc000b15100, 0x52800a0, 0xc00279bd00, 0xc002d35800)\n\t/usr/local/Cellar/go/1.12.5/libexec/src/net/http/server.go:2375 +0x1d6\ngithub.com/tendermint/tendermint/rpc/lib/server.maxBytesHandler.ServeHTTP(0x5267080, 0xc000b15100, 0xf4240, 0x52800a0, 0xc00279bd00, 0xc002d35800)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.32.0/rpc/lib/server/http_server.go:178 +0xd0\ngithub.com/tendermint/tendermint/rpc/lib/server.RecoverAndLogHandler.func1(0x52807e0, 0xc0032f20e0, 0xc002d35800)\n\t/Users/sherlock/go/pkg/mod/github.com/irisnet/tendermint@v0.32.0/rpc/lib/server/http_server.go:151 +0x317\nnet/http.HandlerFunc.ServeHTTP(0xc000202c90, 0x52807e0, 0xc0032f20e0, 0xc002d35800)\n\t/usr/local/Cellar/go/1.12.5/libexec/src/net/http/server.go:1995 +0x44\nnet/http.serverHandler.ServeHTTP(0xc000a4dba0, 0x52807e0, 0xc0032f20e0, 0xc002d35800)\n\t/usr/local/Cellar/go/1.12.5/libexec/src/net/http/server.go:2774 +0xa8\nnet/http.(*conn).serve(0xc000946f00, 0x52851e0, 0xc004851d00)\n\t/usr/local/Cellar/go/1.12.5/libexec/src/net/http/server.go:1878 +0x851\ncreated by net/http.(*Server).Serve\n\t/usr/local/Cellar/go/1.12.5/libexec/src/net/http/server.go:2884 +0x2f4\n"

**Comment by haifengxi** [comment]
Return a meaningful error instead of panicking.

**Comment by shilei-wang** [comment]
confirm fixed
