### ISSUE TITLE
Using lots of memory and the node died in v0.16.0-rc0

### ISSUE THREAD

**Issue by kwunyeung** [irisnet/irishub#2069]
My node on `nyancat-5` died yesterday. My service would restart it but it keeps crashing because of `Out of memory` on a 4G memory machine. I expanded the machine with more memory and it eventually can continue to run. The node crashed at height 34560 with the following log.

```
ABCI Replay Blocks                           module=state appHeight=34560 storeHeight=34561 stateHeight=34560
Replay last block using real app             module=state
fatal error: runtime: out of memory
```
When it continues to sync, it was using around 6.3G memory. After the sync is smooth, I restarted the node and it runs with around 600M memory for some time. I am wondering if the replay is processing all the state history which take up so much memory.

**Comment by zhangyelong** [comment]
Thanks for your feedback.
If it only crashed at height 34560, it is reasonable. The `signed_blocks_window` is 34560 blocks, many validators of the previous testnets didn't participate in `nyancat-5`, they got slashed at height 34560 together, which caused a huge calculation at the same block.
We will try to reproduce this issue and see if we can do something to improve the performance.
