### ISSUE TITLE
v0.16.0 snapshot problem

### ISSUE THREAD

**Issue by wjdfx** [irisnet/irishub#2085]
**Describe the bug**
When run command: iris snapshot --home /mnt/data/irisnet/  show error: 

panic: load db failed

After testing found the /mnt/data/irisnet/ folder just has 644 permission, but for run snapshot operation.
I think read permission is enough. 

Even if permission is required, the error should be a permission problem, not a panic problem.

**Comment by zhiqiang-bianjie** [comment]
@wjdfx  Read and write permissions are also required, but this error prompt is indeed not elegant
