### ISSUE TITLE
Prune ivalstore version using rootstore version(block height)

### ISSUE THREAD

**Issue by chengwenxi** [irisnet/irishub#2119]
### Summary

We pruned the app state(each iavlstore tree for each module) version, reserving only the following versions:
* First version
* Recent 100 versions
* Per 10000 versions

The version increased with each commit, so if we load the store on `InitChainer`, the version is block height, but if we load the store on a software upgrade height, the version is `block_height - upgrade_height`. But now we pruned iavlstore version using itself version, so each iavlstore snapshot height(Per 10000 versions) may be different if you loaded each iavlstore on different block height.

So, we can't reset app state to a snapshot height if there are some new modules are added on software upgrade height(height%10000!=0).

### Proposal
Prune ivalstore version using rootstore version(block height).

**Comment by shilei-wang** [comment]
confirm fixed
