### ISSUE TITLE
[p3] Incorrect document indentation format of "service definition"

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#2186]
**To Reproduce**
iriscli service definition a01
ServiceDefinition:
		Name:                  001
		Description:           service-description
		Tags:                  [tag1 tag2]
		Author:                faa1k2smnl4y9fs27nwep7an50sl3fq5kwwe3tnkrd
		AuthorDescription:     author-description
		Schemas:               {
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "title",
    "description": "description",
    "type": "type",

    "input": {
        "type": "object",
        "description": "request data"

**Comment by secret2830** [comment]
Resolved in #https://github.com/irisnet/irishub/pull/2181

**Comment by shilei-wang** [comment]
confirm fixed
