### ISSUE TITLE
[p2] The usage of "Token id" is confused

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#2188]
**Describe the bug**
In some cases， we usd Symbol to specify "Token id" ，for example：
1）iriscli asset token tokens --token-id=btc
2）iriscli bank send --amount=100btc
3）iriscli asset token fee btc

In some cases， we usd i.Symbol to specify "Token id" ，for example：
1）iriscli asset token edit i.a01
2）iriscli asset token mint i.a01

Maybe， we should unify the two expressions！

**Comment by zhiqiang-bianjie** [comment]
@shilei-wang  To be compatible with previous versions of 0.17.0, the unique identifier of the token still uses "token-id", the main unit uses "symobl", and the smallest unit uses "symobl-min". After the new chain starts (1.0). The unique identifier is "symobl", the main unit is "symobl", and the smallest unit is "min-unit"

**Comment by shilei-wang** [comment]
confirm fixed
