### ISSUE TITLE
[p2] "min-unit" could not be used for sending tokens like "iris-atto"

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#2189]
**To Reproduce**
echo 1234567890 | iriscli asset token issue --name=token-name --min-unit="kitty" --scale=0 --initial-supply=10000 --max-supply=30000 --mintable=true  --from=v0 --chain-id=shilei-qa --fee=0.004iris --commit --symbol=a01

echo 1234567890 | iriscli bank send --amount=1kitty --fee=0.004iris --commit --chain-id=shilei-qa --from=v0 --to=faa1lcuw6ewd2gfxap37sejewmta205sgssmv5fnju

**Comment by zhiqiang-bianjie** [comment]
@shilei-wang  "--min-unit" is only for display purposes in version 0.17.0. It can only be tried in version 1.0. The minimum unit is "symbol-min"
