### ISSUE TITLE
Improve service invocation

### ISSUE THREAD

**Issue by secret2830** [irisnet/irishub#2215]
1. Add events
2. Add genesis export
3. Improve by comments by @haifengxi

**Comment by haifengxi** [comment]
Add `SuperMode bool` to `MsgRequestService` and propagate it to `RequestContext` and `Request`, replacing `Profiling bool`.

If `MsgRequestService` has `SuperMode` set to `true` yet the signer is not a superuser (i.e., profiler), then authentication fails and the msg will not be processed.

**Comment by haifengxi** [comment]
Add a new system parameter (governable) `MinDeposit`, with default value of 10000iris.
