### ISSUE TITLE
how to get mainnet peers? help me

### ISSUE THREAD

**Issue by 1971192997** [irisnet/irishub#2250]
how to get mainnet peers? help me

i use the persistent_peers listed on the config.toml but no one can work.
 pls give me some mainnet peers of iris thanks

**Comment by chengwenxi** [comment]
@1971192997 You can get it from here:
https://github.com/irisnet/mainnet/blob/master/config/community-peers.md

**Comment by 1971192997** [comment]
> @1971192997 You can get it from here:
> https://github.com/irisnet/mainnet/blob/master/config/community-peers.md

sorry,i have tried to telnet those ip and port ,but failed

**Comment by 1971192997** [comment]
> @1971192997 You can get it from here:
> https://github.com/irisnet/mainnet/blob/master/config/community-peers.md

telnet 173.249.60.154 26656
telnet 18.196.245.160 26656
telnet electra.iris.forbole.com 26656
telnet irissentry01.dokia.cloud 26656
telnet 92.222.78.22 26656

**Comment by chengwenxi** [comment]
I tested and can connect to some of the above nodes using a VPN. We will provide some domestic peer nodes soon.

**Comment by chengwenxi** [comment]
or you can join our QQ group for help: 834063323

**Comment by 1971192997** [comment]
> I tested and can connect to some of the above nodes using a VPN. We will provide some domestic peer nodes soon.

thanks a lot
