### ISSUE TITLE
Add system schemas and related logic

### ISSUE THREAD

**Issue by haifengxi** [irisnet/irishub#2260]
- Update service module spec
- Store two _system-level_ schemas during module init, namely: `pricing` and `result`
- Allow users to query system schema by name
- `result` schema has two mandatory properties: `code` (integer enum of 200, 400, 500) and `message` (string)
- Service definition schemas comprise of `input` and `output` only
- If `output` is valid OR `output` is invalid/non-existent yet `result.code != 200`, then the response is considered _valid_; otherwise the response is deemed as _invalid_
- For a valid response, service fee shall be released to provider
- An invalid response is treated the same way as a timed-out request: service fee returned to consumer and binding deposit slashed
- For module-initiated service requests, only responses containing a valid `output` are _usable_ for the callback

**Comment by secret2830** [comment]
Current implementation:
  1. Pricing schema already exists
  2. Only valid outputs as params in the module callback

**Comment by secret2830** [comment]
Is it more reasonable to release the service fee to provider only when the result.Code == 200 and output is valid?

**Comment by chengwenxi** [comment]
Agreed.
