### ISSUE TITLE
Persistent peers do not reconnect

### ISSUE THREAD

**Issue by mdyring** [irisnet/irishub#2379]
**Describe the bug**
I have noticed that persistent peers will be "lost" over time. Initially when iris is started, a connection will be established but eventually it will be lost due to network disconnect or timeout.

**Version**
Using 0.16.2-e7226031-2-mainnet. Similar behaviour was observed on earlier releases as well.

**To Reproduce**
Remove and re-establish network connectivity. Dynamically added peers (via /dial_peers RPC) reconnect, but this might be due to the RPC being invoked periodically and not the address book.

**Expected behavior**
Persistent peers (actually all peers in addrbook) should be retried again periodically. 

**Additional context**
Nothing in logs related to this. Tried searching for the peer id, but nothing turned up with log_level = "main:info,state:info,mempool:info,*:error". 

I looked in addrbook.json and two things stood out:

1) "attempts" is 0 for all peers, even ones I know to have been briefly disconnected.
2) "attempts" is also 0 for the persistent peer in question.

```
{
        "addrs": [
                {
                        "addr": {
                                "id": "54dcd7c9bd47e3dab56ea984f62a4d958191bf60",
                                "ip": "<ipv6-address>",
                                "port": 27656
                        },
                        "src": {
                                "id": "57995a81de571e2abbd513f9bf0949804ccc952c",
                                "ip": "::",
                                "port": 27656
                        },
                        "attempts": 0,
                        "last_attempt": "2020-06-19T00:09:57.391908402+02:00",
                        "last_success": "2020-06-19T00:09:57.391908402+02:00",
                        "bucket_type": 2,
                        "buckets": [

```

**Comment by chengwenxi** [comment]
I believe it has been fixed on the tendermint layer.
