### ISSUE TITLE
Signing with latest Ledger Cosmos application fails

### ISSUE THREAD

**Issue by mdyring** [irisnet/irishub#2380]
**Describe the bug**
After updating to the latest Ledger Cosmos application, the iriscli returns this error:
```
ERROR: please open Cosmos app on the Ledger device - error: error fetching public key: [APDU_CODE_INS_NOT_SUPPORTED] Instruction code not supported or invalid
```

This is a well known issue that has been fixed in Cosmos gaia:
https://github.com/cosmos/cosmos-sdk/issues/5223
https://github.com/cosmos/cosmos-sdk/pull/5224
https://github.com/cosmos/cosmos-sdk/pull/6305

**To Reproduce**
Install latest Cosmos application using Ledger Live.

**Comment by ebuchman** [comment]
Hi folks, any idea when this might be addressed?

**Comment by zhangyelong** [comment]
> Hi folks, any idea when this might be addressed?

Working on this :)

**Comment by chengwenxi** [comment]
https://github.com/irisnet/irishub/commit/4d4c06a6dfdccc4271734ef6eef95960f000384f fixed it.

**Comment by zhangyelong** [comment]
@mdyring @ebuchman Thanks for your report, could you give it a try: [v0.16.3](https://github.com/irisnet/irishub/releases/tag/v0.16.3)
