### ISSUE TITLE
when the node sync the data,got something wrong,as follows. ERROR: error during handshake: error on replay: wrong Block.Header.AppHash. Expected

### ISSUE THREAD

**Issue by 1971192997** [irisnet/irishub#2387]
when the node sync the data,got something wrong,as follows.
ERROR: error during handshake: error on replay: wrong Block.Header.AppHash. Expected

and can U help slove this problem?

**Comment by zhangyelong** [comment]
Could you describe your environment, mainnet or testnet, irishub version, etc.

**Comment by 1971192997** [comment]
hava reset the node.... but thanks
