### ISSUE TITLE
install iris failed

### ISSUE THREAD

**Issue by xihucuyu888** [irisnet/irishub#2516]
**Describe the bug**
make install
go install -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=iris -X github.com/cosmos/cosmos-sdk/version.AppName=iris -X github.com/cosmos/cosmos-sdk/version.Version=1.0.0-rc0 -X github.com/cosmos/cosmos-sdk/version.Commit=6b2443abf5e6e2297d621e708a4f7d66374afb22 -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger" -X github.com/cosmos/cosmos-sdk/types.reDnmString=[a-zA-Z][a-zA-Z0-9/:]{2,127}' ./cmd/iris
#github.com/zondax/hid
vendor/github.com/zondax/hid/hid_enabled.go:23:31: fatal error: os/threads_posix.c: No such file or directory
compilation terminated.
Makefile:93: recipe for target 'install' failed
make: *** [install] Error 2

version: v1.0.0-rc0

**Comment by chengwenxi** [comment]
@xihucuyu888 Thanks for your report! Could you provide the your machine information?
