### ISSUE TITLE
problem in install iris 

### ISSUE THREAD

**Issue by cryptocoin1btc** [irisnet/irishub#2531]
when i make - make install
make: statik: Command not found
Makefile:89: recipe for target 'update_irislcd_swagger_docs' failed
make: *** [update_irislcd_swagger_docs] Error 127

**Comment by curelight** [comment]
same here,

make get_tools install

make: *** [Makefile:89: update_irislcd_swagger_docs] Error 127

**Comment by chengwenxi** [comment]
@cryptocoin1btc @curelight There is a high probability that the `GOBIN` is not added to the `PATH`, see https://github.com/irisnet/irishub/blob/master/docs/get-started/install.md#install-go.

**Comment by bayten** [comment]
Checked everything, still cannot install iris.

**Comment by chengwenxi** [comment]
@bayten Is there any error returned? Is it returning the above error?

**Comment by bayten** [comment]
It is returning the error above. OS: Linux Mint 20.1. Go version: 1.13.8 linux/amd 64

**Comment by chengwenxi** [comment]
@bayten Please ensure the `statik` is installed in `GOBIN`,
```bash
ls $GOBIN | grep statik
```
If `statik` is found, seems that the `GOBIN` is not added to `PATH` correctly.
