### ISSUE TITLE
Refactor irishub sdk

### ISSUE THREAD

**Issue by chengwenxi** [irisnet/irishub#2626]
## Summary

Now, irishub-sdk contains all modules in one repo, we plan to split them into core-sdk and multiple repos(for each module), so that users can assemble them without add all modules.

### Implementing

* [ ] [go-sdk](https://github.com/irisnet/irishub-sdk-go)

**Comment by Nicke-lucky** [comment]
core-sdk 
The Core-SDK contains the following core functions

Auth module;

Bank module;

Keys module;

Keys requires an interface designed to support SM2 (for the federation chain IRITA)
At present, Keys is mainly the entrance, and the actual logic is in Crypto

base_client. go

**Comment by zhangyelong** [comment]
Closing in favor of https://github.com/irisnet/core-sdk-go/issues/10
