### ISSUE TITLE
Error: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain

### ISSUE THREAD

**Issue by xysblob** [irisnet/irishub#2631]
**Iris version ** 
v1.0.1

**Environment**
OS
 
**What happened**
ERROR: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain 

**genesis.json**
https://raw.githubusercontent.com/irisnet/mainnet/master/config/genesis.json

When I followed the steps in https://irisnet.org/docs/get-started/mainnet.html#run-a-full-node and run **iris start** to start a full node, an handshake error occurred:

**Logs**
iris--mainnetnode systemd[1]: Started Iris Node.
 iris--mainnetnode : 1:23AM INF starting ABCI with Tendermint
 iris--mainnetnode : 1:23AM INF Starting multiAppConn service impl={"Logger":{}} module=proxy
 iris--mainnetnode : 1:23AM INF Starting localClient service connection=query impl="marshaling error: json: unsupported type: abcicli.Callback" module=abci-client
 iris--mainnetnode : 1:23AM INF Starting localClient service connection=snapshot impl="marshaling error: json: unsupported type: abcicli.Callback" module=abci-client
 iris--mainnetnode : 1:23AM INF Starting localClient service connection=mempool impl="marshaling error: json: unsupported type: abcicli.Callback" module=abci-client
 iris--mainnetnode : 1:23AM INF Starting localClient service connection=consensus impl="marshaling error: json: unsupported type: abcicli.Callback" module=abci-client
 iris--mainnetnode : 1:23AM INF Starting EventBus service impl={"Logger":{}} module=events
 iris--mainnetnode : 1:23AM INF Starting PubSub service impl={"Logger":{}} module=pubsub
 iris--mainnetnode : 1:23AM INF Starting IndexerService service impl={"Logger":{}} module=txindex
 iris--mainnetnode : 1:23AM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=
 iris--mainnetnode : 1:23AM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
 iris--mainnetnode : 1:23AM INF asserting crisis invariants inv=0/11 module=x/crisis
 iris--mainnetnode : 1:23AM INF asserting crisis invariants inv=1/11 module=x/crisis
 iris--mainnetnode : 1:23AM INF asserting crisis invariants inv=2/11 module=x/crisis
 iris--mainnetnode : 1:23AM INF asserting crisis invariants inv=3/11 module=x/crisis
 iris--mainnetnode : 1:23AM INF asserting crisis invariants inv=4/11 module=x/crisis
 iris--mainnetnode : 1:23AM INF asserting crisis invariants inv=5/11 module=x/crisis
 iris--mainnetnode : 1:23AM INF asserting crisis invariants inv=6/11 module=x/crisis
 iris--mainnetnode : 1:23AM INF asserting crisis invariants inv=7/11 module=x/crisis
 iris--mainnetnode : 1:23AM INF asserting crisis invariants inv=8/11 module=x/crisis
 iris--mainnetnode : 1:23AM INF asserting crisis invariants inv=9/11 module=x/crisis
 iris--mainnetnode : 1:23AM INF asserting crisis invariants inv=10/11 module=x/crisis
 iris--mainnetnode : 1:23AM INF asserted all invariants duration=1.31777 height=0 module=x/crisis
 iris--mainnetnode : 1:23AM INF created new capability module=ibc name=ports/transfer
 iris--mainnetnode : 1:23AM INF port binded module=x/ibc/port port=transfer
 iris--mainnetnode : 1:23AM INF claimed capability capability=1 module=transfer name=ports/transfer
 iris--mainnetnode : Error: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain

**Comment by zhangyelong** [comment]
1. Please check your `home` directory, if you are not using the default `~/.iris`, you need to run `iris start --home=<your_home>`
2. Try `iris unsafe_reset_all --home=<your_home>` before restart

**Comment by xysblob** [comment]
Thank you I was able to do a `iris start` after an unsafe reset, yet another error occurred `Error: listen tcp 0.0.0.0:26656: bind: address already in use`, and when I run `iris status`, `Error: post failed: Post "http://localhost:26657": dial tcp 127.0.0.1:26657: connect: connection refused`, I did a check using `sudo netstat -pna | grep <port>` and I don't see any process is using these ports, any idea what might went wrong?
