### ISSUE TITLE
@jingniao thanks for your report. We have updated the get start docs, plz have a try.

### ISSUE THREAD

**Issue by Xiechengqi** [irisnet/irishub#2638]
@jingniao thanks for your report. We have updated the get start docs, plz have a try.

_Originally posted by @chengwenxi in https://github.com/irisnet/irishub/issues/2609#issuecomment-812356680_

这个问题我安装过程又遇到了 。。。希望能出个 Q&A，不会 Go 表示很头疼

**Comment by jingniao** [comment]
https://github.com/irisnet/irishub/blob/master/docs/get-started/mainnet.md
意思是，需要使用v1.0.1版本的开始同步，同步到指定高度之后再升级到v1.1.1 同步之后的块，而不能用v1.1.x版本的直接从0开始同步。

**Comment by Xiechengqi** [comment]
> https://github.com/irisnet/irishub/blob/master/docs/get-started/mainnet.md
> 意思是，需要使用v1.0.1版本的开始同步，同步到指定高度之后再升级到v1.1.1 同步之后的块，而不能用v1.1.x版本的直接从0开始同步。

谢谢老哥，希望官方文档多加一行解释
