### ISSUE TITLE
ERR dialing failed (attempts: 6): auth failure: secret conn failed

### ISSUE THREAD

**Issue by Xiechengqi** [irisnet/irishub#2673]
**Describe the bug**

IRIS Testnet 区块同步异常终止

**Screenshots**

![1009_01](https://user-images.githubusercontent.com/26536442/136646960-8b550e6f-f02e-4f81-9c6f-529d5a697f51.jpg)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Version: 1.1.1

**Comment by zhangyelong** [comment]
Closing stale issue, if you still have problems on this issue, please reopen it :)
