### ISSUE TITLE
Please provide amd64 and arm64 release binaries for Linux

### ISSUE THREAD

**Issue by mdyring** [irisnet/irishub#2699]
**Is your feature request related to a problem? Please describe.**

When deploying the build process might occasionally fail if unable to download source files from a github repository.

It would save time (both human but also computer/compile time) to simply provide release binaries.

**Describe the solution you'd like**

Similar to other Cosmos projects, please provide a "Releases" page that contains amd64 and arm64 binaries for Linux. For validators running on AWS it is beneficial to offer arm64 since this is a cost-efficient deployment option.

**Comment by zhangyelong** [comment]
No problem, will add to CI workflow soon :)

**Comment by aofengli** [comment]
Expired issue, I will close it
