### ISSUE TITLE
 panic: UPGRADE "v1.1" NEEDED at time: 2021-03-31T14:00:00Z

### ISSUE THREAD

**Issue by airstring** [irisnet/irishub#2731]
**Describe the bug**
 When I upgraded the program to version v1.2.1,then there was an error:
        panic: UPGRADE "v1.1" NEEDED at time: 2021-03-31T14:00:00Z:

**To Reproduce**
1. I emptied the data directory and restarted several times, but still encountered the same error.

**Comment by dreamer-zq** [comment]
@airstring irishub has undergone several major upgrades, so it is not recommended that you start syncing from a very old version, you can use the v1.2.0 version and use the state sync method to catch up with blocks

**Comment by oncloudit** [comment]
1. if you emptied the data directory and restarted, you need use irishub v1.0.0 to start from beginning and when the node stop syncing blocks, change irishub version and restart it. its neither convenient nor quick so it's not recommend;
2. you can find a snapshot or a data directory backup from other normal node, like: https://storage.googleapis.com/irisnet/irishub-snapshot-2021-11-22.tgz, and start sync block from that data;
3. https://www.irisnet.org/docs/get-started/state-sync.html
try state sync to start a node from recently block height, it's more quickly、conveniently and saving storage, except there is no longer history blocks in your node. 
hope help you some a bit.
