### ISSUE TITLE
Add Slack app to the repo

### ISSUE THREAD

**Issue by sgerogia** [irisnet/irishub#2750]
**Is your feature request related to a problem? Please describe.**
We would like to get notifications of upcoming releases in an automated way. 

**Describe the solution you'd like**
It would be a massive help if we could do it through [Github's Slack](https://github.com/apps/slack/installations/new) integration.

**Describe alternatives you've considered**
Subscribing to public chain channels: this is manual and we can easily miss updates

**Additional context**

**Comment by aofengli** [comment]
Expired issue, I will close it
