### ISSUE TITLE
GetTxsEvent is broken for HTLC related events after bumping cosmos SDK.

### ISSUE THREAD

**Issue by artemii235** [irisnet/irishub#2769]
https://github.com/cosmos/cosmos-sdk/issues/13858

**Comment by artemii235** [comment]
UPD: it's already fixed in Cosmos SDK and back ported to https://github.com/cosmos/cosmos-sdk/tree/release/v0.46.x.

**Comment by aofengli** [comment]
> UPD: it's already fixed in Cosmos SDK and back ported to https://github.com/cosmos/cosmos-sdk/tree/release/v0.46.x.

Thank you for your reminder, after the new release of Cosmos-SDK is released, we will update it as soon as possible

**Comment by artemii235** [comment]
@aofengli Thanks! The new release is published: https://github.com/cosmos/cosmos-sdk/releases/tag/v0.46.5. They even retracted all previous `0.46.*` releases.

**Comment by artemii235** [comment]
@aofengli As I can see, Cosmos SDK version was bumped in IRIS. Is it going to be released soon?

**Comment by aofengli** [comment]
> @aofengli As I can see, Cosmos SDK version was bumped in IRIS. Is it going to be released soon?

Yes, we are doing some tests.

**Comment by aofengli** [comment]
@artemii235 Upgrade completed
