### ISSUE TITLE
v1.4.0 panic

### ISSUE THREAD

**Issue by hzccc** [irisnet/irishub#2772]
**Describe the bug**
Upgrade v1.4.0 panic 

**To Reproduce**
1. git checkout v1.4.0
2. make install 
3. restart iris

![image](https://user-images.githubusercontent.com/20179548/202391263-b7db649b-cfd2-473c-a67c-99c4ae6c1f73.png)

**Comment by aofengli** [comment]
> **Describe the bug** Upgrade v1.4.0 panic
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. git checkout v1.4.0
> 2. make install
> 3. restart iris
> 
> ![image](https://user-images.githubusercontent.com/20179548/202391263-b7db649b-cfd2-473c-a67c-99c4ae6c1f73.png)

The proposal for v1.4.0 is expected to start on 2022-11-25 and close on 2022-11-30. For now, please continue to run your node with v1.3.1 @hzccc
