### ISSUE TITLE
Upgrade to version 1.4.1

### ISSUE THREAD

**Issue by airstring** [irisnet/irishub#2786]
The startup command is as follows：
./iris-linux-amd64 start \
  --home  /iris  \
  --fast_sync \
  --moniker  iris-mainnet \
  --rpc.laddr tcp://0.0.0.0:26657 \
  --grpc.address 0.0.0.0:26659 \
  --p2p.laddr tcp://0.0.0.0:26656 

But a long time has passed without log output！

os:  amazon linux2
cpu/mem: 4C/16G

**Comment by aofengli** [comment]
Is it resolved now? If it is not resolved, we can provide you with an upgraded snapshot, please follow our discord

**Comment by aofengli** [comment]
Long time no reply, close
