### ISSUE TITLE
1.4.1 Nodes do not synchronize data

### ISSUE THREAD

**Issue by COLUD4** [irisnet/irishub#2789]
After upgrading the node to 1.4.1, the data is not synchronized and I can't even use statesync, [[statesync]
# State sync rapidly bootstraps a new node by discovering, fetching, and restoring a state machine
# snapshot from peers instead of fetching and replaying historical blocks. Requires some peers in
# the network to take and serve state machine snapshots. State sync is not attempted if the node
# has any local state (LastBlockHeight > 0). The node will have a truncated block history,
# starting from the height of the snapshot.
enable = true

# RPC servers (comma-separated) for light client verification of the synced state machine and
# retrieval of state data for node bootstrapping. Also needs a trusted height and corresponding
# header hash obtained from a trusted source, and a period during which validators can be trusted.
#
# For Cosmos SDK-based chains, trust_period should usually be about 2/3 of the unbonding time (~2
# weeks) during which they can be financially punished (slashed) for misbehavior.
rpc_servers = "34.82.96.8:26657,34.77.68.145:26657"
trust_height = 17690874
trust_hash = "BE27D6CD0AB22A0A3DE32CD2C02FA8AFB666901CCC3971E34C80C9C3275EEDD3"
trust_period = "168h0m0s"] look at the log probably because I can't connect to peer.

**Comment by aofengli** [comment]
Same issue as https://github.com/irisnet/irishub/issues/2791: Please set pruning in apptoml to pruning = noting
