### ISSUE TITLE
panic: cannot delete latest saved version (48)

### ISSUE THREAD

**Issue by Jackwumingjie** [irisnet/irishub#2790]
I build the node v1.4.1 in ubuntu20.04 and golang 1.19.3. I sync the node with snapshot https://storage.googleapis.com/irisnet/irishub-1-data-v1.4.1.tar.lz4. But the node show as the picture 
<img width="1256" alt="企业微信截图_56fd1be2-0ead-46ef-be90-bda0aef328a1" src="https://user-images.githubusercontent.com/39093109/205863474-f6b1a83a-7110-4017-ad30-06502cf868c3.png">

**Comment by aofengli** [comment]
Same issue as [\#2791](https://github.com/irisnet/irishub/issues/2791): Please set pruning in apptoml to pruning = noting
