### ISSUE TITLE
Version 2.0.0  upgrade problem

### ISSUE THREAD

**Issue by airstring** [irisnet/irishub#2837]
After the node is upgraded to 2.0.0, an error occurs when the node is started.

iris    | Chain options: iris start --home /chain/data --fast_sync --moniker iris-mainnet --rpc.laddr tcp://0.0.0.0:26657 --grpc.address 0.0.0.0:26659 --p2p.laddr tcp://0.0.0.0:26656
iris    | 3:29AM INF Unlocking keyring
iris    | 3:29AM INF starting ABCI with Tendermint
iris    | 3:30AM INF starting node with ABCI Tendermint in-process
iris    | 3:30AM INF service start impl=multiAppConn module=proxy msg={} server=node
iris    | 3:30AM INF service start connection=query impl=localClient module=abci-client msg={} server=node
iris    | 3:30AM INF service start connection=snapshot impl=localClient module=abci-client msg={} server=node
iris    | 3:30AM INF service start connection=mempool impl=localClient module=abci-client msg={} server=node
iris    | 3:30AM INF service start connection=consensus impl=localClient module=abci-client msg={} server=node
iris    | 3:30AM INF service start impl=EventBus module=events msg={} server=node
iris    | 3:30AM INF service start impl=PubSub module=pubsub msg={} server=node
iris    | 3:30AM INF service start impl=IndexerService module=txindex msg={} server=node
iris    | 3:30AM INF ABCI Handshake App Info hash="���\n�\x11\x022��i9=֭�\x18O��~��E\x1dc٦P�Q�" height=19456864 module=consensus protocol-version=0 server=node software-version=2.0.0
iris    | 3:30AM INF ABCI Replay Blocks appHeight=19456864 module=consensus server=node stateHeight=19456864 storeHeight=19456865
iris    | 3:30AM INF Replay last block using real app module=consensus server=node
iris    | 3:30AM INF Mint parameters inflation_rate=0.040000000000000000 mint_denom=uiris module=mint
iris    | 3:30AM INF Mint result block_provisions=12675235uiris module=mint
iris    | 3:30AM INF minted coins from module account amount=12675235uiris from=mint module=x/bank
iris    | panic: runtime error: invalid memory address or nil pointer dereference
iris    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x79b9c8]
iris    |
iris    | goroutine 1 [running]:
iris    | math/big.(*Int).Mul(0xc082348b60, 0xc082348b60, 0x0)
iris    |       /usr/local/go/src/math/big/int.go:167 +0xa8
iris    | github.com/cosmos/cosmos-sdk/types.Dec.MulMut({0x2bd0f40?}, {0xc0823a4bc8?})
iris    |       /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.9/types/decimal.go:292 +0x28
iris    | github.com/cosmos/cosmos-sdk/types.Dec.ImmutOp({0x3a0a730?}, 0x3549568, {0x39d5b88?})
iris    |       /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.9/types/decimal.go:235 +0x162
iris    | github.com/cosmos/cosmos-sdk/types.Dec.Mul(...)
iris    |       /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.9/types/decimal.go:287
iris    | github.com/evmos/ethermint/x/feemarket/keeper.(*Keeper).EndBlock(_, {{0x39f4d58, 0xc000058068}, {0x3a0b1b0, 0xc075e9c1c0}, {{0xb, 0x0}, {0xc075507520, 0x9}, 0x128e361, ...}, ...}, ...)
iris    |       /root/go/pkg/mod/github.com/bianjieai/ethermint@v0.20.0-irishub-1/x/feemarket/keeper/abci.go:54 +0x392
iris    | github.com/evmos/ethermint/x/feemarket.AppModule.EndBlock(...)
iris    |       /root/go/pkg/mod/github.com/bianjieai/ethermint@v0.20.0-irishub-1/x/feemarket/module.go:142
iris    | github.com/cosmos/cosmos-sdk/types/module.(*Manager).EndBlock(_, {{0x39f4d58, 0xc000058068}, {0x3a0b1b0, 0xc075e9c1c0}, {{0xb, 0x0}, {0xc075507520, 0x9}, 0x128e361,...}, ...}, ...)
iris    |       /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.9/types/module/module.go:505 +0x482
iris    | github.com/irisnet/irishub/app.(*IrisApp).EndBlocker(_, {{0x39f4d58, 0xc000058068}, {0x3a0b1b0, 0xc075e9c1c0}, {{0xb, 0x0}, {0xc075507520, 0x9}, 0x128e361, ...}, ...}, ...)
iris    |       /root/go/src/github.com/irisnet/irishub/app/app.go:664 +0x79
iris    | github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).EndBlock(0xc000630e00, {0x20?})
iris    |       /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.9/baseapp/abci.go:206 +0x165
iris    | github.com/tendermint/tendermint/abci/client.(*localClient).EndBlockSync(0xc01c91f1a0, {0xc01c91f1a0?})
iris    |       /root/go/pkg/mod/github.com/informalsystems/tendermint@v0.34.26/abci/client/local_client.go:288 +0xdf
iris    | github.com/tendermint/tendermint/proxy.(*appConnConsensus).EndBlockSync(0xc075dd9560?, {0x20?})
iris    |       /root/go/pkg/mod/github.com/informalsystems/tendermint@v0.34.26/proxy/app_conn.go:89 +0x24
iris    | github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x39f64c0?, 0xc013e38f60}, {0x3a01820, 0xc02698e2f0}, 0xc000e9c780, {0x3a0be78, 0xc026248b40}, 0x128e360?)
iris    |       /root/go/pkg/mod/github.com/informalsystems/tendermint@v0.34.26/state/execution.go:327 +0x55f
iris    | github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0x0, 0x0}}, {0xc0268382b0, 0x9}, 0x8b9058, 0x128e360, {{0xc02da9b3c0, ...}, ...}, ...}, ...)
iris    |       /root/go/pkg/mod/github.com/informalsystems/tendermint@v0.34.26/state/execution.go:140 +0x171
iris    | github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(_, {{{0xb, 0x0}, {0x0, 0x0}}, {0xc0268382b0, 0x9}, 0x8b9058, 0x128e360, {{0xc02da9b3c0, ...}, ...}, ...}, ...)
iris    |       /root/go/pkg/mod/github.com/informalsystems/tendermint@v0.34.26/consensus/replay.go:503 +0x23c
iris    | github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x0, 0x0}}, {0xc0268382b0, 0x9}, 0x8b9058, 0x128e360, {{0xc02da9b3c0, ...}, ...}, ...}, ...)
iris    |       /root/go/pkg/mod/github.com/informalsystems/tendermint@v0.34.26/consensus/replay.go:416 +0x7ae
iris    | github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc00b3a12d0, {0x3a0df30, 0xc01b3f2b60})
iris    |       /root/go/pkg/mod/github.com/informalsystems/tendermint@v0.34.26/consensus/replay.go:268 +0x3d4
iris    | github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x0, 0x0}}, {0xc0268382b0, 0x9}, 0x8b9058, 0x128e360, ...}, ...)
iris    |       /root/go/pkg/mod/github.com/informalsystems/tendermint@v0.34.26/node/node.go:329 +0x1b8
iris    | github.com/tendermint/tendermint/node.NewNode(0xc001370000, {0x39f0bd0, 0xc0011d17c0}, 0xc001346740, {0x39ccae0, 0xc016ced9e0}, 0x1?, 0x54689e0?, 0xc001346ab0, {0x39f64c0, ...}, ...)
iris    |       /root/go/pkg/mod/github.com/informalsystems/tendermint@v0.34.26/node/node.go:777 +0x597
iris    | github.com/irisnet/irishub/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x3a1fc80, 0xc001893e90}, 0x0, {0x0, 0x0}, {0x3a13f98, ...}, ...}, ...)
iris    |       /root/go/src/github.com/irisnet/irishub/server/start.go:342 +0xf27
iris    | github.com/irisnet/irishub/server.StartCmd.func2(0xc00173d200?, {0xc0011ece70?, 0x0?, 0xb?})
iris    |       /root/go/src/github.com/irisnet/irishub/server/start.go:127 +0x1ec
iris    | github.com/spf13/cobra.(*Command).execute(0xc00173d200, {0xc0011ecdc0, 0xb, 0xb})
iris    |       /root/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
iris    | github.com/spf13/cobra.(*Command).ExecuteC(0xc001669500)
iris    |       /root/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
iris    | github.com/spf13/cobra.(*Command).Execute(...)
iris    |       /root/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
iris    | github.com/spf13/cobra.(*Command).ExecuteContext(...)
iris    |       /root/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:961
iris    | github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x260ba00?, {0x0, 0x0}, {0xc000dc1fa0, 0xb})
iris    |       /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.9/server/cmd/execute.go:36 +0x20f
iris    | main.main()
iris    |       /root/go/src/github.com/irisnet/irishub/cmd/iris/main.go:17 +0x30
iris exited with code 2

**Comment by haifengxi** [comment]
You should have followed the [upgrade procedure](https://github.com/irisnet/mainnet/blob/master/upgrade/v2.0.0.md).
