### ISSUE TITLE
修改validator信息结果有误

### ISSUE THREAD

**Issue by jianghua001** [irisnet/irishub#348]
测试网：fuxi-3001
执行： 【ubuntu@irisnet-test-fuxi:~$ iriscli stake edit-validator --details="I am bryant666" --from=bryant666 --address-validator=faa19323sq8hqsdm3z6rdv0uempfgy8aykgg37wehg --chain-id=fuxi-3001 --fee=400000000000000iris --gas=20000】
结果：把name改为了主机名hostname：irisnet-test-fuxi。
![image](https://user-images.githubusercontent.com/38059344/46255576-1f788080-c4d1-11e8-8c5a-ef870f8a2759.png)

**Comment by wukongcheng** [comment]
Thanks for the report. We have debugged the issue and report to the cosmos-sdk.

https://github.com/cosmos/cosmos-sdk/issues/2423
