### ISSUE TITLE
Timed out waiting for transaction to be included in a block but transaction did committed

### ISSUE THREAD

**Issue by kwunyeung** [irisnet/irishub#351]
I'm sending tx on fuxi-3001.

```
iriscli stake delegate --address-delegator faa1ezdq3058narjxzyuw0e6h40u4ywr96wzhjmzw4 --address-validator faa1ezdq3058narjxzyuw0e6h40u4ywr96wzhjmzw4 --amount 20iris --from ky3001 --memo kwunyeung-3B84437810397048 --chain-id=fuxi-3001 --node="http://120.79.226.163:26657" --fee 40000000000000000iris  --gas=200000
```

Then it doesn't response until time out.

```
ERROR: broadcast_tx_commit: Response error: RPC error -32603 - Internal error: Timed out waiting for transaction to be included in a block
```

However, the tx did committed and it can be found on the explorer.

https://testnet.irisplorer.io/#/tx?txHash=7487646E6CD395EF80A088FCD272D3A89DB16DF3

**Comment by kidinamoto01** [comment]
Hey, @kwunyeung 
Thanks for your report.
my guess is, the node you submitted the tx to, was having trouble syncing, so the iriscli didn't receive a valid response in time. Somehow, your tx was broadcasted to its peers and got executed. In this way, its shown in explorer.  

In our testnet, the seed nodes you connected to had performance issue, and we will definitely look into it.
