### ISSUE TITLE
[record issue]The return value (ConsumedTxFee) of "record submit" is unreadable , it would be better if we return the escaped characters. 

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#450]
hey， @yunkunrao 
Earlier today, i have a preliminary test for the record feature. Some issues were noticed.

For example , "completeConsumedTxFee-iris-atto": "\u0001\u0001\u0001H\ufffdH\u0000" . This kind of return value is unfriendly and not acceptable, it would be better if we return the escaped characters insteadof unreadable unicode or whatever.

**Comment by chengwenxi** [comment]
it's added by me for simulation test, I will fix it.
