### ISSUE TITLE
[record issue]The result of boundary test shows that we cannot upload onchain-data which size "EQUALS" 1024 bytes

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#451]
hey， @yunkunrao 

The spec describes the size of onchain data should "NOT MORE THAN" 1024 bytes, the result of boundary test shows that we cannot upload onchain-data size "EQUALS" 1024 bytes

Test results FYI:
upload data (size=1023 bytes) ==> accepted  ok
upload data (size=1024 bytes) ==> rejected (Fail to meet expectations)
upload data (size=1025 bytes) ==> rejected  ok

**Comment by yunkunrao** [comment]
Yes, it's a boundary mistake, this issue was fixed by this commit 78b58774f.
