### ISSUE TITLE
Example of unrevoke in iriscli is wrong

### ISSUE THREAD

**Issue by kwunyeung** [irisnet/irishub#589]
The current example of unrevoke read like this.

```
Examples:
iriscli stake unrevoke --to=<account address> --from <key name> --fee=0.004iris --chain-id=<chain-id>
```
but the command should be without `--to=<account address>`.

**Comment by HaoyangLiu** [comment]
Thanks for your feedback. 
It was our mistaken. This issue has be fixed in next release 0.7.0. And the comand has been changed too. The new command will be `iriscli stake unjail`.
