### ISSUE TITLE
[priority:p0] [stake genesis initialization] Encountered CONSENSUS FAILURE while restarting irisnet, caused by improperly initialize jailed-validator data

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#909]
**Describe the bug**
Encountered CONSENSUS FAILURE while restarting irisnet, cause by improperly initialize jailed-validator  data

**To Reproduce**
1. Lanch 4 irishub validator nodes
2. Force one of the validators offline
3. Wait several minutes until it is unbonded
4. Terminate the rest validator nodes
5. Export Genesis.json
6. Copy and replace 4 Genesis.json with the old ones
7. Restart 4 nodes (Encountered CONSENSUS FAILURE)

**Expected behavior**
New irisnet restart smoothly

**Screenshots**
Error msg:
CONSENSUS FAILURE!!!                         module=consensus err="invariant broken: loose token invariance:\n\tbank.LooseTokens: 7999858736000000000000000\n\tsum of account tokens: 7999957736000000000000000" stack="goroutine 114 [running]:\nruntime/debug.Stack(0xc000919480, 0xed32e0, 0xc000b5f600)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine.func2(0xc0009a8700, 0x1194e50)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:583 +0x57\npanic(0xed32e0, 0xc000b5f600)\n\t/usr/local/go/src/runtime/panic.go:513 +0x1b9\ngithub.com/irisnet/irishub/app/v0.(*ProtocolVersion0).assertRuntimeInvariants(0xc000247800, 0x1297380, 0xc0008dea20, 0xc00023a980, 0x11)\n\t/root/go/src/github.com/irisnet/irishub/app/v0/invariants.go:26 +0x12e\ngithub.com/irisnet/irishub/app/v0.(*ProtocolVersion0).EndBlocker(0xc000247800, 0x1297380, 0xc0008dea20, 0xc00023a980, 0x11, 0x1, 0x0, 0x0, 0x0, 0x0, ...)\n\t/root/go/src/github.com/irisnet/irishub/app/v0/protocol_v0.go:277 +0x3ea\ngithub.com/irisnet/irishub/app/v0.(*ProtocolVersion0).EndBlocker-fm(0x1297380, 0xc0008dea20, 0xc00023a980, 0x11, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/root/go/src/github.com/irisnet/irishub/app/v0/protocol_v0.go:396 +0xc8\ngithub.com/irisnet/irishub/app.(*BaseApp).EndBlock(0xc000af8240, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/root/go/src/github.com/irisnet/irishub/app/baseapp.go:822 +0x809\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/abci/client.(*localClient).EndBlockSync(0xc0009d0ba0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/abci/client/local_client.go:239 +0xea\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/proxy.(*appConnConsensus).EndBlockSync(0xc0008eb9f0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/proxy/app_conn.go:77 +0x51\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state.execBlockOnProxyApp(0x1297fc0, 0xc00090bd20, 0x129d480, 0xc0008eb9f0, 0xc000b783c0, 0xc0008de930, 0x12a1be0, 0xc00019e0c8, 0x0, 0x0, ...)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state/execution.go:277 +0x701\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc0009b3340, 0x8, 0x0, 0xc000a1def0, 0x6, 0xc000a1df00, 0x9, 0x0, 0x0, 0x0, ...)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state/execution.go:104 +0x146\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).finalizeCommit(0xc0009a8700, 0x1)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1302 +0xa42\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).tryFinalizeCommit(0xc0009a8700, 0x1)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1233 +0x451\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit.func1(0xc0009a8700, 0x0, 0x1)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1179 +0x90\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit(0xc0009a8700, 0x1, 0x0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1210 +0x6b8\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).addVote(0xc0009a8700, 0xc000ac41e0, 0xc00003f380, 0x28, 0x1196088, 0x107, 0xc000831ac0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1634 +0xc03\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).tryAddVote(0xc0009a8700, 0xc000ac41e0, 0xc00003f380, 0x28, 0xc00096e120, 0x107, 0x107)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1481 +0x59\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).handleMsg(0xc0009a8700, 0x128b7c0, 0xc0001ae210, 0xc00003f380, 0x28)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:662 +0x696\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine(0xc0009a8700, 0x0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:619 +0x682\ncreated by github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).OnStart\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:306 +0x132\n"

**Desktop (please complete the following information):**
- 4 validator nodes

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by HaoyangLiu** [comment]
This is not a bug in exporting genesis. This bug locates in stake genesis initialization. I will fix this bug soon.

**Comment by shilei-wang** [comment]
> This is not a bug in exporting genesis. This bug locates in stake genesis initialization. I will fix this bug soon.

Thank you for your information， updated issue discription

**Comment by HaoyangLiu** [comment]
@shilei-wang 
Fixed! Please verify.

**Comment by shilei-wang** [comment]
verified
