### ISSUE TITLE
[priority:p0] Unbond a validator entirely before its commission is distributed triggers CONSENSUS FAILURE

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#916]
**Describe the bug**
Unbond a validator entirely before its commission is distributed triggers CONSENSUS FAILURE

**To Reproduce**
1. Start 2 nodes (voting power=100,100)
2. Unbond a validator entirely before its commission is distributed
    a.iriscli keys show v1 --bech val
    b.iriscli stake unbond --address-validator=fva1ydx46mv7g4qdqhjm80m074a85cx27sxvqq64jq --shares-percent=1 --fee=0.004iris --from=v1 --chain-id=shilei-qa
    c.iriscli stake validators
3. Wait 10 mintues until unbonding time is passed
4. CONSENSUS FAILURE Triggered

**Expected behavior**
N/A

**Screenshots**
CONSENSUS FAILURE!!!                         module=consensus err="Should not delete validator with unwithdrawn validator commission" stack="goroutine 109 [running]:\nruntime/debug.Stack(0xc000c31a68, 0xe8a120, 0x1283100)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine.func2(0xc0001b1180, 0x1194e50)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:583 +0x57\npanic(0xe8a120, 0x1283100)\n\t/usr/local/go/src/runtime/panic.go:513 +0x1b9\ngithub.com/irisnet/irishub/modules/distribution/keeper.Keeper.RemoveValidatorDistInfo(0x128eca0, 0xc0001c3290, 0xc0000c8ee0, 0xc0000c8ee0, 0x128eca0, 0xc0001c32f0, 0x128ece0, 0xc0001c3300, 0xc000a99c00, 0x5, ...)\n\t/root/go/src/github.com/irisnet/irishub/modules/distribution/keeper/validator.go:45 +0x2fe\ngithub.com/irisnet/irishub/modules/distribution/keeper.Keeper.onValidatorRemoved(0x128eca0, 0xc0001c3290, 0xc0000c8ee0, 0xc0000c8ee0, 0x128eca0, 0xc0001c32f0, 0x128ece0, 0xc0001c3300, 0xc000a99c00, 0x5, ...)\n\t/root/go/src/github.com/irisnet/irishub/modules/distribution/keeper/hooks.go:54 +0xc2\ngithub.com/irisnet/irishub/modules/distribution/keeper.Hooks.OnValidatorRemoved(0x128eca0, 0xc0001c3290, 0xc0000c8ee0, 0xc0000c8ee0, 0x128eca0, 0xc0001c32f0, 0x128ece0, 0xc0001c3300, 0xc000a99c00, 0x5, ...)\n\t/root/go/src/github.com/irisnet/irishub/modules/distribution/keeper/hooks.go:110 +0xc2\ngithub.com/irisnet/irishub/app/v0.Hooks.OnValidatorRemoved(0x128eca0, 0xc0001c3290, 0xc0000c8ee0, 0xc0000c8ee0, 0x128eca0, 0xc0001c32f0, 0x128ece0, 0xc0001c3300, 0xc000a99c00, 0x5, ...)\n\t/root/go/src/github.com/irisnet/irishub/app/v0/protocol_v0.go:421 +0xf2\ngithub.com/irisnet/irishub/modules/stake/keeper.Keeper.RemoveValidator(0x128eca0, 0xc0001c3260, 0x128ece0, 0xc0001c3270, 0xc0000c8ee0, 0x12a1d60, 0xc00000dcc0, 0x129f1c0, 0xc000b2a120, 0xc0000c8ee0, ...)\n\t/root/go/src/github.com/irisnet/irishub/modules/stake/keeper/validator.go:202 +0x57b\ngithub.com/irisnet/irishub/modules/stake/keeper.Keeper.UnbondAllMatureValidatorQueue(0x128eca0, 0xc0001c3260, 0x128ece0, 0xc0001c3270, 0xc0000c8ee0, 0x12a1d60, 0xc00000dcc0, 0x129f1c0, 0xc000b2a120, 0xc0000c8ee0, ...)\n\t/root/go/src/github.com/irisnet/irishub/modules/stake/keeper/validator.go:392 +0x613\ngithub.com/irisnet/irishub/modules/stake.EndBlocker(0x1297380, 0xc002c7daa0, 0xc002cbe2c0, 0xd, 0x128eca0, 0xc0001c3260, 0x128ece0, 0xc0001c3270, 0xc0000c8ee0, 0x12a1d60, ...)\n\t/root/go/src/github.com/irisnet/irishub/modules/stake/handler.go:50 +0x128\ngithub.com/irisnet/irishub/app/v0.(*ProtocolVersion0).EndBlocker(0xc00023ca00, 0x1297380, 0xc002c7daa0, 0xc002cbe2c0, 0xd, 0x11, 0x0, 0x0, 0x0, 0x0, ...)\n\t/root/go/src/github.com/irisnet/irishub/app/v0/protocol_v0.go:273 +0x157\ngithub.com/irisnet/irishub/app/v0.(*ProtocolVersion0).EndBlocker-fm(0x1297380, 0xc002c7daa0, 0xc002cbe2c0, 0xd, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/root/go/src/github.com/irisnet/irishub/app/v0/protocol_v0.go:396 +0xc8\ngithub.com/irisnet/irishub/app.(*BaseApp).EndBlock(0xc000abe180, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/root/go/src/github.com/irisnet/irishub/app/baseapp.go:822 +0x809\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/abci/client.(*localClient).EndBlockSync(0xc000c4ca80, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/abci/client/local_client.go:239 +0xea\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/proxy.(*appConnConsensus).EndBlockSync(0xc00006f610, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/proxy/app_conn.go:77 +0x51\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state.execBlockOnProxyApp(0x1297fc0, 0xc00000d600, 0x129d480, 0xc00006f610, 0xc002bd2f00, 0xc002c7d410, 0x12a1be0, 0xc0000bc5a8, 0x1, 0xc002c32380, ...)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state/execution.go:277 +0x701\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc0007fe000, 0x8, 0x0, 0xc0009c04d0, 0x6, 0xc0009c04e0, 0x9, 0x10, 0x1, 0xc002c32380, ...)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state/execution.go:104 +0x146\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).finalizeCommit(0xc0001b1180, 0x11)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1302 +0xa42\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).tryFinalizeCommit(0xc0001b1180, 0x11)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1233 +0x451\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit.func1(0xc0001b1180, 0x0, 0x11)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1179 +0x90\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit(0xc0001b1180, 0x11, 0x0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1210 +0x6b8\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).addVote(0xc0001b1180, 0xc002c70dc0, 0x0, 0x0, 0x4c6b4d, 0xc002c121e0, 0xc00020eb00)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1634 +0xc03\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).tryAddVote(0xc0001b1180, 0xc002c70dc0, 0x0, 0x0, 0x42cc82, 0xc000000008, 0xc000c35b70)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1481 +0x59\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).handleMsg(0xc0001b1180, 0x128b7c0, 0xc0027c1218, 0x0, 0x0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:662 +0x696\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine(0xc0001b1180, 0x0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:623 +0x567\ncreated by github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).OnStart\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:306 +0x132\n"

**Desktop (please complete the following information):**
- 2 validator nodes

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by HaoyangLiu** [comment]
This issue is fixed. Please verify.

**Comment by shilei-wang** [comment]
Verified

**Comment by shilei-wang** [comment]
TODO：

**Comment by wukongcheng** [comment]
Looks like the same problem as before reopen. Just one happens in the Endblock and one happens in the second unbond. @HaoyangLiu

**Comment by shilei-wang** [comment]
Bug still exist， keep issue open
