### ISSUE TITLE
Normalize broadcast response

### ISSUE THREAD

**Issue by HaoyangLiu** [irisnet/irishub#924]
Currently we support three broadcast types: 
1. `sync`: Return after CheckTx is done
2. `async`: Return immediately
3. `commit`: Return after the transaction is included by a block
Now, the response schemas are much different and don't follow our standard reponse schema. We will design a standard reponse schema.

**Comment by HaoyangLiu** [comment]
@haifengxi Is the current response schema acceptable?

**Comment by haifengxi** [comment]
Acceptable.  Closing this issue...
