### ISSUE TITLE
[known issues] Propose block with invalid data

### ISSUE THREAD

**Issue by wukongcheng** [irisnet/irishub#928]
**Describe the bug**
When it's your turn to produce a block, use invalid data to construct a block, causing garbage data to be stored on the chain.

https://github.com/cosmos/cosmos-sdk/issues/2687

**Comment by haifengxi** [comment]
We'll introduce a mechanism where the malefactor's stake get slashed in this case.

**Comment by wukongcheng** [comment]
Related issue: https://github.com/irisnet/irishub/issues/1052 will solve this issue.
