### ISSUE TITLE
[known issues] Propose block with txs which will fail verification on the last signature 

### ISSUE THREAD

**Issue by wukongcheng** [irisnet/irishub#929]
**Describe the bug**
When it is your turn to produce a block, the included Tx will fail verification on the last signature, causing the CPU of other nodes to perform a large number of invalid signature verification operations.

**Comment by haifengxi** [comment]
Proposer censorship will be punished by slashing the malefactor's stake.

**Comment by wukongcheng** [comment]
Related issue: https://github.com/irisnet/irishub/issues/1052 will solve this issue.
