### ISSUE TITLE
[priority:p2] Gov fail to verify the identity of trustee before withdrawing fee tax from the blockchain's tax pool

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#933]
Describe the bug
Gov verify the identity of trustee while submitting proposal but not after vote through

To Reproduce

    1. execute add-trustee to add one trustee (eg. user_1)
    2. submit a TxTaxUsage proposal (specify --dest-address=user_1_faa)
    3. execute delete-trustee to remove user_1 from trustee list
    4. vote "yes" for the previous proposal

    notice that tax fee is withdrawed to a non-trustee account

Expected behavior
check the identity of trustee before withdrawing fee tax

Screenshots
N/A

Desktop (please complete the following information):

    1 validator nodes

Smartphone (please complete the following information):
N/A

Additional context
N/A

**Comment by chengwenxi** [comment]
Are we check this account is trustee again on governance Execute? @haifengxi

**Comment by haifengxi** [comment]
Yes, let's do that. thanks  @chengwenxi

**Comment by chengwenxi** [comment]
Please verify and close.

**Comment by shilei-wang** [comment]
Verified
