### ISSUE TITLE
Bond Height for validators not set correctly

### ISSUE THREAD

**Issue by kidinamoto01** [irisnet/irishub#950]
**Describe the bug**

In Fuxi-7000 testnet, when query the validator info, the `bond height` filed seems wrong. For non-genesis validators, its 
 
**To Reproduce**

1. `iriscli stake validator fva1nzgvvfam8n4lskkcqmhes07td6wkum9c3x2wkm  --node=localhost:26657`

**Expected behavior**

After `create-validator`,https://testnet.irisplorer.io/#/tx?txHash=C301DF275B5B016AF6884543817C57BAF37CBCA786C4CCEAB07213C0FD9347E4 

The `bond height` should be 1456

**Screenshots**
```
Validator
Operator Address: fva1nzgvvfam8n4lskkcqmhes07td6wkum9c3x2wkm
Validator Consensus Pubkey: fvp1zcjduepqee548lnq4whxzd8lqvgexw520h54ncnze8cc0w4mypvd20eqdvssz2jgvl
Jailed: false
Status: Bonded
Tokens: 4999.0000000000
Delegator Shares: 4999.0000000000
Description: {clawmvp.xyz C257B58E89DF7D10 clawmvp.xyz What u seek is seeking you.}
Bond Height: 0
Unbonding Height: 0
Minimum Unbonding Time: 1970-01-01 00:00:00 +0000 UTC
Commission: {{0.1000000000 0.2000000000 0.0100000000 2018-12-29 09:02:24.97504674 +0000 UTC}}
```
**Desktop (please complete the following information):**
 - OS: ubuntu 16.04

**Comment by haifengxi** [comment]
https://testnet.irisplorer.cn/#/validators/3/active shows the correct bond height, so this should be a cli bug.

**Comment by HaoyangLiu** [comment]
The root reason is the same as https://github.com/cosmos/cosmos-sdk/issues/2909.
We have already fixed this issue in v.0.10.0, please refer to this PR: https://github.com/irisnet/irishub/pull/864
