### ISSUE TITLE
[priority:p0] DivideByZeroException is thrown when an attempt to unbond validators' shares to a small amount, which causes CONSENSUS FAILURE

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#952]
**Describe the bug**
DivideByZeroException is thrown when an attempt to unbond validators' shares to a small amount, which causes CONSENSUS FAILURE

**To Reproduce**
1. Start 2 nodes (voting power=100,100)
2. iriscli stake unbond --address-validator=v0_fva --shares-amount=99.6 --fee=0.004iris --commit --from=v0 --chain-id=shilei-qa
3. iriscli stake unbond --address-validator=v1_fva --shares-amount=99.6 --fee=0.004iris --commit --from=v1 --chain-id=shilei-qa
4. DivideByZeroException is thrown , CONSENSUS FAILURE Triggered

**Expected behavior**
N/A

**Screenshots**
CONSENSUS FAILURE!!!                         module=consensus err="division by zero" stack="goroutine 119 [running]:\nruntime/debug.Stack(0xc0009f84e8, 0xe8b180, 0x1289c40)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine.func2(0xc00083a700, 0x11961e0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:583 +0x57\npanic(0xe8b180, 0x1289c40)\n\t/usr/local/go/src/runtime/panic.go:513 +0x1b9\nmath/big.nat.div(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/usr/local/go/src/math/big/nat.go:643 +0x452\nmath/big.(*Int).QuoRem(0xc002bd8080, 0xc002bd8080, 0xc002bd80a0, 0xc0009f8750, 0x0, 0x0)\n\t/usr/local/go/src/math/big/int.go:232 +0xbf\nmath/big.(*Int).Div(0xc002bd8080, 0xc002bd8080, 0xc002bd80a0, 0xc002bd8060)\n\t/usr/local/go/src/math/big/int.go:243 +0x6d\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/types.(*ValidatorSet).computeAvgProposerPriority(0xc0018ca5d0, 0x14)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/types/validator_set.go:125 +0xef\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/types.(*ValidatorSet).shiftByAvgProposerPriority(0xc0018ca5d0, 0xc002bd8060)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/types/validator_set.go:135 +0x2f\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/types.(*ValidatorSet).incrementProposerPriority(0xc0018ca5d0, 0x1, 0x1)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/types/validator_set.go:104 +0x299\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/types.(*ValidatorSet).IncrementProposerPriority(0xc0018ca5d0, 0x1)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/types/validator_set.go:86 +0x7b\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state.updateState(0x8, 0x0, 0xc000b4e0c0, 0x6, 0xc000b4e0d0, 0x9, 0x26, 0x1, 0xc000036be0, 0x20, ...)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state/execution.go:452 +0x9f\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc0008bc620, 0x8, 0x0, 0xc000b4e0c0, 0x6, 0xc000b4e0d0, 0x9, 0x26, 0x1, 0xc000036be0, ...)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state/execution.go:133 +0x4c8\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).finalizeCommit(0xc00083a700, 0x27)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1302 +0xa42\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).tryFinalizeCommit(0xc00083a700, 0x27)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1233 +0x451\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).addProposalBlockPart(0xc00083a700, 0xc000afb920, 0xc00088c2a0, 0x28, 0xc00283c800, 0x3c8, 0x3c8)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1472 +0x4d1\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).handleMsg(0xc00083a700, 0x128cda0, 0xc000afb920, 0xc00088c2a0, 0x28)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:650 +0x7a0\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine(0xc00083a700, 0x0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:619 +0x682\ncreated by github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).OnStart\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:306 +0x132\n"

**Desktop (please complete the following information):**
- 2 validator nodes

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by HaoyangLiu** [comment]
This is not a bug. 
In your case, all validators are removed. This is a suicide operation.
