### ISSUE TITLE
Addresses returned from `iriscli tendermint validator-set` does not correspond to their validators

### ISSUE THREAD

**Issue by gin** [irisnet/irishub#957]
## Describe the bug
Addresses returned from `iriscli tendermint validator-set` does not correspond to their validators.  
Delegating tokens to an address from the returned response results in error message:  
```sh
ERROR: Msg 0 failed: {"codespace":"stake","code":101,"message":"validator does not exist for that address"}
```
Comparing a known valid validator's `fva` address and `fvp` pub_key (with `iriscli keys show <NAME> --bech=val`) against the response from `iriscli tendermint validator-set` shows that the `address` and `pub_key` values in the response are incorrect.  
This is with `iriscli version` = `0.9.0`.  

## To Reproduce
1. Query for the list of active validators
e.g. `iriscli tendermint validator-set --chain-id=fuxi-7000 | jq`
2. Pick a validator address from the list to delegate some tokens to
e.g.
```sh
iriscli stake delegate \
    --address-validator=fva134ntthn9a30347x440h62x5ml6xz5tvrranet2 \
    --amount=1iris \
    --from=soju \
    --memo=soju-FB687932653925BDB4A23EEEE63CFC4FA120D5D8 \
    --fee=0.01iris \
    --chain-id=fuxi-7000
````
3. Type in key name's password
`ERROR: Msg 0 failed: {"codespace":"stake","code":101,"message":"validator does not exist for that address"}`

## Expected behavior
Expect response from `iriscli tendermint validator-set` to have correct values for `address` and `pub_key`.  
`voting_power` value is correct.  

**For example**  
The `address`  
`fva134ntthn9a30347x440h62x5ml6xz5tvrranet2`  
from `iriscli tendermint validator-set --chain-id=fuxi-7000` should be  
`fva1fs9pmwvyf7pc5dwr2k78lgar5nyc0uqg6lvlar`  

The `pub_key`  
`fvp1zcjduepqlue7usk94zdn5s2z98defnv48qfsghsa6lletvs6h3vk4lz0q5zqjpfhqk`  
from `iriscli tendermint validator-set --chain-id=fuxi-7000` should be  
`fvp1addwnpepqtwxc3pud78pr8x2yzu7z6qpzth7q8l36k5vcyp249qktgfau66lqz6xp93`  

<img width="1091" alt="screenshot" src="https://user-images.githubusercontent.com/1329429/50544500-44ea5880-0bac-11e9-8bb7-710dc015c989.png">

## Additional context
Found this bug when doing task 3 (Delegate some iris to a validator) from https://github.com/irisnet/testnets/tree/master/fuxi/fuxi-7000, but to a validator that is not ourselves.

**Comment by chengwenxi** [comment]
The command
```shell
iriscli tendermint validator-set
```
show tendermint validator set.

You can run
```shell
iriscli stake validators 
```
to get the application validator set, the result contains your validator operator address `fva1fs9pmwvyf7pc5dwr2k78lgar5nyc0uqg6lvlar ` which same as the result of 
```shell
iriscli keys show soju --bech=val
```

**Comment by gin** [comment]
👍 
Oops! I see. Thanks!
