### ISSUE TITLE
[priority:p0] CONSENSUS breaks immediately after Gov/SystemHalt passed, Obviously, it doesn't meet the expectation

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#975]
**CONSENSUS breaks right after SystemHalt passed, the panic msg hints it was a bug , not an expected behavior.**

----
message:

CONSENSUS FAILURE!!!                         module=consensus err="UnmarshalJSON expects a pointer" stack="goroutine 12 [running]:\nruntime/debug.Stack(0xc003d4c110, 0xeda9e0, 0xc0033b6ac0)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine.func2(0xc0000e7180, 0x119c1f0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:583 +0x57\npanic(0xeda9e0, 0xc0033b6ac0)\n\t/usr/local/go/src/runtime/panic.go:513 +0x1b9\ngithub.com/irisnet/irishub/modules/params/subspace.Subspace.Get(0xc0000b2380, 0x1298540, 0xc00006cca0, 0x1298580, 0xc00006ccb0, 0xc000037420, 0x3, 0x19, 0xc000b840c0, 0x12a0c20, ...)\n\t/root/go/src/github.com/irisnet/irishub/modules/params/subspace/subspace.go:80 +0x151\ngithub.com/irisnet/irishub/modules/gov.Keeper.GetSystemHaltPeriod(0xc0000b2380, 0x1298540, 0xc00006cca0, 0x1298580, 0xc00006ccb0, 0xc000b3de30, 0xc0000b2380, 0x1298540, 0xc00006cca0, 0x1298580, ...)\n\t/root/go/src/github.com/irisnet/irishub/modules/gov/govparams_util.go:161 +0xff\ngithub.com/irisnet/irishub/modules/gov.SystemHaltProposalExecute(0x12a0c20, 0xc003c42780, 0xc00259d600, 0xd, 0xc0000b2380, 0x1298540, 0xc00006cca0, 0x1298580, 0xc00006ccb0, 0xc000b3de30, ...)\n\t/root/go/src/github.com/irisnet/irishub/modules/gov/execute.go:93 +0x23c\ngithub.com/irisnet/irishub/modules/gov.Execute(0x12a0c20, 0xc003c42780, 0xc00259d600, 0xd, 0xc0000b2380, 0x1298540, 0xc00006cca0, 0x1298580, 0xc00006ccb0, 0xc000b3de30, ...)\n\t/root/go/src/github.com/irisnet/irishub/modules/gov/execute.go:15 +0x2f8\ngithub.com/irisnet/irishub/modules/gov.EndBlocker(0x12a0c20, 0xc003c42780, 0xc00259d600, 0xd, 0xc0000b2380, 0x1298540, 0xc00006cca0, 0x1298580, 0xc00006ccb0, 0xc000b3de30, ...)\n\t/root/go/src/github.com/irisnet/irishub/modules/gov/handler.go:268 +0x2398\ngithub.com/irisnet/irishub/app/v0.(*ProtocolVersion0).EndBlocker(0xc000227100, 0x12a0c20, 0xc003c42780, 0xc00259d600, 0xd, 0x10f, 0x0, 0x0, 0x0, 0x0, ...)\n\t/root/go/src/github.com/irisnet/irishub/app/v0/protocol_v0.go:250 +0xc1\ngithub.com/irisnet/irishub/app/v0.(*ProtocolVersion0).EndBlocker-fm(0x12a0c20, 0xc003c42780, 0xc00259d600, 0xd, 0x10f, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/root/go/src/github.com/irisnet/irishub/app/v0/protocol_v0.go:368 +0xc8\ngithub.com/irisnet/irishub/app.(*BaseApp).EndBlock(0xc000c16180, 0x10f, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/root/go/src/github.com/irisnet/irishub/app/baseapp.go:829 +0x809\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/abci/client.(*localClient).EndBlockSync(0xc000aec900, 0x10f, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/abci/client/local_client.go:239 +0xea\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/proxy.(*appConnConsensus).EndBlockSync(0xc000195c80, 0x10f, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/proxy/app_conn.go:77 +0x51\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state.execBlockOnProxyApp(0x12a1a20, 0xc000b92380, 0x12a6e40, 0xc000195c80, 0xc0036cd680, 0xc00254dfb0, 0x12ab480, 0xc00019e930, 0x7, 0xc0033b4180, ...)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state/execution.go:277 +0x701\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc0000b3dc0, 0x8, 0x0, 0xc000a387c0, 0x6, 0xc000a387d0, 0x9, 0x10e, 0x7, 0xc0033b4180, ...)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state/execution.go:104 +0x146\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).finalizeCommit(0xc0000e7180, 0x10f)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1302 +0xa42\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).tryFinalizeCommit(0xc0000e7180, 0x10f)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1233 +0x451\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit.func1(0xc0000e7180, 0x0, 0x10f)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1179 +0x90\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit(0xc0000e7180, 0x10f, 0x0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1210 +0x6b8\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).addVote(0xc0000e7180, 0xc00269f360, 0x0, 0x0, 0x4c665d, 0xc002ef5b60, 0xc000b83600)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1634 +0xc03\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).tryAddVote(0xc0000e7180, 0xc00269f360, 0x0, 0x0, 0x42cc82, 0xc000000008, 0xc003d4fb70)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1481 +0x59\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).handleMsg(0xc0000e7180, 0x1295060, 0xc0034b3170, 0x0, 0x0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:662 +0x696\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine(0xc0000e7180, 0x0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:623 +0x567\ncreated by github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).OnStart\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:306 +0x132\n"

**Comment by wukongcheng** [comment]
```func (keeper Keeper) GetSystemHaltPeriod(ctx sdk.Context) ( SystemHaltPeriod int64) {
	keeper.paramSpace.Get(ctx,KeySystemHaltPeriod,SystemHaltPeriod)
	return
}```

Should use the &SystemHaltPeriod in keeper.paramSpace.Get

**Comment by shilei-wang** [comment]
Verified
