### ISSUE TITLE
[priority:p0] Loose token invariance found in a very special case for an unknown reason. (CONSENSUS breaks)

### ISSUE THREAD

**Issue by shilei-wang** [irisnet/irishub#981]
**Since I've tried my best to reproduce the bug for 2h
DO NOT try to modify any data in reproduce steps (the bug only works with the following parameters):**

* develop   8174e64a467b99461eeb5560a3fbd92183cb76e6
v0-power=100 v1-power=100
important_penalty = 0.0007000000

echo 1234567890 | iriscli gov submit-proposal --title="t" --description="t" --type="ParameterChange" --deposit="2000iris"  --param='stake/UnbondingTime=0h1m0s' --from=v0 --chain-id=shilei-qa --fee=0.004iris  --commit

echo 1234567890 | iriscli stake unbond --address-validator=v1_fva --shares-amount=99.6 --fee=0.004iris --commit --from=v1 --chain-id=shilei-qa

echo 1234567890 | iriscli stake delegate --address-validator=v1_fva --amount=1iris --fee=0.004iris --commit  --from=v1  --chain-id=shilei-qa
echo 1234567890 | iriscli stake delegate --address-validator=v1_fva --amount=1iris --fee=0.004iris --commit  --from=v0  --chain-id=shilei-qa

no one vote, wait until slashing...

echo 1234567890 | iriscli stake unbond --address-validator=v1_fva --shares-percent=1 --fee=0.004iris --commit --from=v1 --chain-id=shilei-qa
echo 1234567890 | iriscli stake unbond --address-validator=v1_fva --shares-percent=1 --fee=0.004iris --commit --from=v0 --chain-id=shilei-qa

Loose token invariance, chain break!

--------------------------

CONSENSUS FAILURE!!!                         module=consensus err="invariant broken: loose token invariance:\n\tbank.LooseTokens: 3999499000000000000000000\n\tsum of account tokens: 3999499000000000020000000" stack="goroutine 48 [running]:\nruntime/debug.Stack(0xc00082f3c0, 0xeda840, 0xc003328eb0)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine.func2(0xc000b35500, 0x119c230)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:583 +0x57\npanic(0xeda840, 0xc003328eb0)\n\t/usr/local/go/src/runtime/panic.go:513 +0x1b9\ngithub.com/irisnet/irishub/app/v0.(*ProtocolV0).assertRuntimeInvariants(0xc000b22000, 0x12a11a0, 0xc0023d6c60, 0xc0030c7580, 0xd)\n\t/root/go/src/github.com/irisnet/irishub/app/v0/invariants.go:31 +0x340\ngithub.com/irisnet/irishub/app/v0.(*ProtocolV0).EndBlocker(0xc000b22000, 0x12a11a0, 0xc0023d6c60, 0xc0030c7580, 0xd, 0x65, 0x0, 0x0, 0x0, 0x0, ...)\n\t/root/go/src/github.com/irisnet/irishub/app/v0/protocol_v0.go:272 +0x3ef\ngithub.com/irisnet/irishub/app/v0.(*ProtocolV0).EndBlocker-fm(0x12a11a0, 0xc0023d6c60, 0xc0030c7580, 0xd, 0x65, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/root/go/src/github.com/irisnet/irishub/app/v0/protocol_v0.go:385 +0xc8\ngithub.com/irisnet/irishub/app.(*BaseApp).EndBlock(0xc000232240, 0x65, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/root/go/src/github.com/irisnet/irishub/app/baseapp.go:829 +0x89d\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/abci/client.(*localClient).EndBlockSync(0xc0000bd260, 0x65, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/abci/client/local_client.go:239 +0xea\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/proxy.(*appConnConsensus).EndBlockSync(0xc00084b520, 0x65, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/proxy/app_conn.go:77 +0x51\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state.execBlockOnProxyApp(0x12a1fa0, 0xc0008a6b20, 0x12a73c0, 0xc00084b520, 0xc003ce7e00, 0xc0023d6630, 0x12aba00, 0xc00000e290, 0x7, 0xc00264be80, ...)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state/execution.go:277 +0x701\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc0000c6540, 0x8, 0x0, 0xc000034380, 0x6, 0xc000034390, 0x9, 0x64, 0x7, 0xc00264be80, ...)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/state/execution.go:104 +0x146\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).finalizeCommit(0xc000b35500, 0x65)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1302 +0xa42\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).tryFinalizeCommit(0xc000b35500, 0x65)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1233 +0x451\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit.func1(0xc000b35500, 0x0, 0x65)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1179 +0x90\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit(0xc000b35500, 0x65, 0x0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1210 +0x6b8\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).addVote(0xc000b35500, 0xc0023c0c80, 0x0, 0x0, 0x4c665d, 0xc0026802a0, 0xc002861900)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1634 +0xc03\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).tryAddVote(0xc000b35500, 0xc0023c0c80, 0x0, 0x0, 0x42cc82, 0xc000000008, 0xc000831b70)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:1481 +0x59\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).handleMsg(0xc000b35500, 0x1295660, 0xc00347bbb8, 0x0, 0x0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:662 +0x696\ngithub.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine(0xc000b35500, 0x0)\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:623 +0x567\ncreated by github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).OnStart\n\t/root/go/src/github.com/irisnet/irishub/vendor/github.com/tendermint/tendermint/consensus/state.go:306 +0x132\n"

**Comment by HaoyangLiu** [comment]
This issue was caused by the precion truncate in delegate share rate calculation. I will fix this issue soon.

**Comment by shilei-wang** [comment]
verified
